// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type KanbanAttachment struct {
	ID          int32            `json:"id"`
	Filename    string           `json:"filename"`
	StorageKey  string           `json:"storage_key"`
	ContentType string           `json:"content_type"`
	SizeBytes   int32            `json:"size_bytes"`
	CardID      int32            `json:"card_id"`
	Context     string           `json:"context"`
	AuthorID    pgtype.Int4      `json:"author_id"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
}

type KanbanBoard struct {
	ID              int32            `json:"id"`
	Title           string           `json:"title"`
	Position        float64          `json:"position"`
	KanbanProjectID int32            `json:"kanban_project_id"`
	CreatedByID     int32            `json:"created_by_id"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	UpdatedAt       pgtype.Timestamp `json:"updated_at"`
	DeletedAt       pgtype.Timestamp `json:"deleted_at"`
}

type KanbanCard struct {
	ID            int32            `json:"id"`
	Title         string           `json:"title"`
	Description   pgtype.Text      `json:"description"`
	Position      float64          `json:"position"`
	DueDate       pgtype.Timestamp `json:"due_date"`
	Priority      pgtype.Text      `json:"priority"`
	IsArchived    bool             `json:"is_archived"`
	ArchivedAt    pgtype.Timestamp `json:"archived_at"`
	ArchivedByID  pgtype.Int4      `json:"archived_by_id"`
	CompletedAt   pgtype.Timestamp `json:"completed_at"`
	CompletedByID pgtype.Int4      `json:"completed_by_id"`
	ColumnID      int32            `json:"column_id"`
	CreatedByID   pgtype.Int4      `json:"created_by_id"`
	BorderColor   pgtype.Text      `json:"border_color"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
}

type KanbanCardActivity struct {
	ID        int32            `json:"id"`
	CardID    int32            `json:"card_id"`
	UserID    pgtype.Int4      `json:"user_id"`
	Type      string           `json:"type"`
	OldValue  pgtype.Text      `json:"old_value"`
	NewValue  pgtype.Text      `json:"new_value"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type KanbanCardAssignee struct {
	CardID int32 `json:"card_id"`
	UserID int32 `json:"user_id"`
}

type KanbanCardComment struct {
	ID        int32            `json:"id"`
	Body      string           `json:"body"`
	CardID    int32            `json:"card_id"`
	AuthorID  int32            `json:"author_id"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type KanbanCardLabel struct {
	KanbanCardID  int32 `json:"kanban_card_id"`
	KanbanLabelID int32 `json:"kanban_label_id"`
}

type KanbanCardSubtask struct {
	ID       int32       `json:"id"`
	Title    string      `json:"title"`
	Status   string      `json:"status"`
	Position float64     `json:"position"`
	CardID   int32       `json:"card_id"`
	UserID   pgtype.Int4 `json:"user_id"`
}

type KanbanColumn struct {
	ID          int32   `json:"id"`
	Title       string  `json:"title"`
	HeaderColor string  `json:"header_color"`
	Position    float64 `json:"position"`
	BoardID     int32   `json:"board_id"`
}

type KanbanLabel struct {
	ID      int32  `json:"id"`
	Name    string `json:"name"`
	Color   string `json:"color"`
	BoardID int32  `json:"board_id"`
}

type KanbanProject struct {
	ID          int32            `json:"id"`
	Name        string           `json:"name"`
	Description pgtype.Text      `json:"description"`
	OwnerID     int32            `json:"owner_id"`
	CreatedByID pgtype.Int4      `json:"created_by_id"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
	DeletedAt   pgtype.Timestamp `json:"deleted_at"`
}

type KanbanProjectUser struct {
	ID              int32       `json:"id"`
	KanbanProjectID int32       `json:"kanban_project_id"`
	UserID          int32       `json:"user_id"`
	Role            string      `json:"role"`
	FolderID        pgtype.Int4 `json:"folder_id"`
	Position        float64     `json:"position"`
}

type KanbanProjectUserFolder struct {
	ID        int32            `json:"id"`
	Name      string           `json:"name"`
	UserID    int32            `json:"user_id"`
	Position  float64          `json:"position"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type User struct {
	ID         int32            `json:"id"`
	Login      string           `json:"login"`
	Lastname   string           `json:"lastname"`
	Firstname  string           `json:"firstname"`
	Patronymic pgtype.Text      `json:"patronymic"`
	AvatarName pgtype.Text      `json:"avatar_name"`
	DeletedAt  pgtype.Timestamp `json:"deleted_at"`
	SyncedAt   pgtype.Timestamp `json:"synced_at"`
}
