// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addCardAssignee = `-- name: AddCardAssignee :exec
INSERT INTO kanban_card_assignee (card_id, user_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddCardAssigneeParams struct {
	CardID int64 `json:"card_id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) AddCardAssignee(ctx context.Context, arg AddCardAssigneeParams) error {
	_, err := q.db.Exec(ctx, addCardAssignee, arg.CardID, arg.UserID)
	return err
}

const addCardLabel = `-- name: AddCardLabel :exec
INSERT INTO kanban_card_label (kanban_card_id, kanban_label_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddCardLabelParams struct {
	KanbanCardID  int64 `json:"kanban_card_id"`
	KanbanLabelID int64 `json:"kanban_label_id"`
}

func (q *Queries) AddCardLabel(ctx context.Context, arg AddCardLabelParams) error {
	_, err := q.db.Exec(ctx, addCardLabel, arg.KanbanCardID, arg.KanbanLabelID)
	return err
}

const addProjectMember = `-- name: AddProjectMember :exec
INSERT INTO kanban_project_user (kanban_project_id, user_id, role, folder_id, position)
VALUES ($1, $2, $3, $4, COALESCE((
    SELECT MAX(p.position) FROM kanban_project_user p
    WHERE p.user_id = $2 AND p.folder_id IS NOT DISTINCT FROM $4
), 0) + 1)
ON CONFLICT (kanban_project_id, user_id) DO UPDATE
SET role = EXCLUDED.role
`

type AddProjectMemberParams struct {
	KanbanProjectID int64       `json:"kanban_project_id"`
	UserID          int64       `json:"user_id"`
	Role            string      `json:"role"`
	FolderID        pgtype.Int8 `json:"folder_id"`
}

// Новая строка участника всегда встаёт в конец личного списка (MAX+1 по user_id/folder_id).
// Перемещение существующей строки — только через UpdateProjectPlacement.
// ponytail: конкурентные вставки одного пользователя могут получить одинаковую позицию;
// порядок добьёт tie-break по id и RebalanceProjectPositions при первом перетаскивании.
func (q *Queries) AddProjectMember(ctx context.Context, arg AddProjectMemberParams) error {
	_, err := q.db.Exec(ctx, addProjectMember,
		arg.KanbanProjectID,
		arg.UserID,
		arg.Role,
		arg.FolderID,
	)
	return err
}

const clearCardAssignees = `-- name: ClearCardAssignees :exec
DELETE FROM kanban_card_assignee
WHERE card_id = $1
`

func (q *Queries) ClearCardAssignees(ctx context.Context, cardID int64) error {
	_, err := q.db.Exec(ctx, clearCardAssignees, cardID)
	return err
}

const columnPositionTaken = `-- name: ColumnPositionTaken :one
SELECT EXISTS(
    SELECT 1 FROM kanban_card
    WHERE column_id = $1 AND parent_id IS NULL AND id <> $2 AND is_archived = FALSE
      AND abs(position - $3::double precision) < 0.0001
)
`

type ColumnPositionTakenParams struct {
	ColumnID pgtype.Int8 `json:"column_id"`
	ID       int64       `json:"id"`
	Position float64     `json:"position"`
}

// Занята ли позиция в целевой колонке. Допуск нужен потому, что позиции дробные
// и приходят от клиента, — точное равенство double precision тут не работает.
// EXISTS выходит на первом совпадении: раньше ради ответа «да/нет» читались и
// ехали по сети все карточки колонки целиком.
// Фильтр тот же, что был у прежней проверки, — только is_archived.
func (q *Queries) ColumnPositionTaken(ctx context.Context, arg ColumnPositionTakenParams) (bool, error) {
	row := q.db.QueryRow(ctx, columnPositionTaken, arg.ColumnID, arg.ID, arg.Position)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createAttachment = `-- name: CreateAttachment :one
INSERT INTO kanban_attachment (filename, storage_key, content_type, size_bytes, context, card_id, author_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, filename, storage_key, content_type, size_bytes, card_id, context, author_id, created_at, deleted_at
`

type CreateAttachmentParams struct {
	Filename    string      `json:"filename"`
	StorageKey  string      `json:"storage_key"`
	ContentType string      `json:"content_type"`
	SizeBytes   int64       `json:"size_bytes"`
	Context     string      `json:"context"`
	CardID      int64       `json:"card_id"`
	AuthorID    pgtype.Int8 `json:"author_id"`
}

func (q *Queries) CreateAttachment(ctx context.Context, arg CreateAttachmentParams) (KanbanAttachment, error) {
	row := q.db.QueryRow(ctx, createAttachment,
		arg.Filename,
		arg.StorageKey,
		arg.ContentType,
		arg.SizeBytes,
		arg.Context,
		arg.CardID,
		arg.AuthorID,
	)
	var i KanbanAttachment
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.StorageKey,
		&i.ContentType,
		&i.SizeBytes,
		&i.CardID,
		&i.Context,
		&i.AuthorID,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createBoard = `-- name: CreateBoard :one
INSERT INTO kanban_board (title, position, kanban_project_id, created_by_id)
VALUES ($1, $2, $3, $4)
RETURNING id, title, position, kanban_project_id, created_by_id, created_at, updated_at, deleted_at, done_column_id
`

type CreateBoardParams struct {
	Title           string  `json:"title"`
	Position        float64 `json:"position"`
	KanbanProjectID int64   `json:"kanban_project_id"`
	CreatedByID     int64   `json:"created_by_id"`
}

func (q *Queries) CreateBoard(ctx context.Context, arg CreateBoardParams) (KanbanBoard, error) {
	row := q.db.QueryRow(ctx, createBoard,
		arg.Title,
		arg.Position,
		arg.KanbanProjectID,
		arg.CreatedByID,
	)
	var i KanbanBoard
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Position,
		&i.KanbanProjectID,
		&i.CreatedByID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DoneColumnID,
	)
	return i, err
}

const createCard = `-- name: CreateCard :one
INSERT INTO kanban_card (title, description, position, due_date, priority, column_id, parent_id, created_by_id, border_color)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, title, description, position, due_date, priority, is_archived, archived_at, archived_by_id, completed_at, completed_by_id, column_id, created_by_id, border_color, created_at, updated_at, deleted_at, parent_id
`

type CreateCardParams struct {
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	Position    float64            `json:"position"`
	DueDate     pgtype.Timestamptz `json:"due_date"`
	Priority    pgtype.Text        `json:"priority"`
	ColumnID    pgtype.Int8        `json:"column_id"`
	ParentID    pgtype.Int8        `json:"parent_id"`
	CreatedByID pgtype.Int8        `json:"created_by_id"`
	BorderColor pgtype.Text        `json:"border_color"`
}

func (q *Queries) CreateCard(ctx context.Context, arg CreateCardParams) (KanbanCard, error) {
	row := q.db.QueryRow(ctx, createCard,
		arg.Title,
		arg.Description,
		arg.Position,
		arg.DueDate,
		arg.Priority,
		arg.ColumnID,
		arg.ParentID,
		arg.CreatedByID,
		arg.BorderColor,
	)
	var i KanbanCard
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Position,
		&i.DueDate,
		&i.Priority,
		&i.IsArchived,
		&i.ArchivedAt,
		&i.ArchivedByID,
		&i.CompletedAt,
		&i.CompletedByID,
		&i.ColumnID,
		&i.CreatedByID,
		&i.BorderColor,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ParentID,
	)
	return i, err
}

const createColumn = `-- name: CreateColumn :one
INSERT INTO kanban_column (title, header_color, position, board_id)
VALUES ($1, $2, $3, $4)
RETURNING id, title, header_color, position, board_id, deleted_at
`

type CreateColumnParams struct {
	Title       string  `json:"title"`
	HeaderColor string  `json:"header_color"`
	Position    float64 `json:"position"`
	BoardID     int64   `json:"board_id"`
}

func (q *Queries) CreateColumn(ctx context.Context, arg CreateColumnParams) (KanbanColumn, error) {
	row := q.db.QueryRow(ctx, createColumn,
		arg.Title,
		arg.HeaderColor,
		arg.Position,
		arg.BoardID,
	)
	var i KanbanColumn
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.HeaderColor,
		&i.Position,
		&i.BoardID,
		&i.DeletedAt,
	)
	return i, err
}

const createComment = `-- name: CreateComment :one
INSERT INTO kanban_card_comment (body, card_id, author_id)
VALUES ($1, $2, $3)
RETURNING id, body, card_id, author_id, created_at, updated_at, deleted_at
`

type CreateCommentParams struct {
	Body     string `json:"body"`
	CardID   int64  `json:"card_id"`
	AuthorID int64  `json:"author_id"`
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (KanbanCardComment, error) {
	row := q.db.QueryRow(ctx, createComment, arg.Body, arg.CardID, arg.AuthorID)
	var i KanbanCardComment
	err := row.Scan(
		&i.ID,
		&i.Body,
		&i.CardID,
		&i.AuthorID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createLabel = `-- name: CreateLabel :one
INSERT INTO kanban_label (name, color, board_id)
VALUES ($1, $2, $3)
RETURNING id, name, color, board_id, deleted_at
`

type CreateLabelParams struct {
	Name    string `json:"name"`
	Color   string `json:"color"`
	BoardID int64  `json:"board_id"`
}

func (q *Queries) CreateLabel(ctx context.Context, arg CreateLabelParams) (KanbanLabel, error) {
	row := q.db.QueryRow(ctx, createLabel, arg.Name, arg.Color, arg.BoardID)
	var i KanbanLabel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.BoardID,
		&i.DeletedAt,
	)
	return i, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO kanban_project (name, description, owner_id, created_by_id)
VALUES ($1, $2, $3, $4)
RETURNING id, name, description, owner_id, created_by_id, created_at, updated_at, deleted_at
`

type CreateProjectParams struct {
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	OwnerID     int64       `json:"owner_id"`
	CreatedByID pgtype.Int8 `json:"created_by_id"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (KanbanProject, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.Name,
		arg.Description,
		arg.OwnerID,
		arg.CreatedByID,
	)
	var i KanbanProject
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.OwnerID,
		&i.CreatedByID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createProjectFolder = `-- name: CreateProjectFolder :one
INSERT INTO kanban_project_user_folder (name, user_id, position)
VALUES ($1, $2, $3)
RETURNING id, name, user_id, position, created_at, updated_at
`

type CreateProjectFolderParams struct {
	Name     string  `json:"name"`
	UserID   int64   `json:"user_id"`
	Position float64 `json:"position"`
}

func (q *Queries) CreateProjectFolder(ctx context.Context, arg CreateProjectFolderParams) (KanbanProjectUserFolder, error) {
	row := q.db.QueryRow(ctx, createProjectFolder, arg.Name, arg.UserID, arg.Position)
	var i KanbanProjectUserFolder
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.UserID,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createProjectHistoryEntry = `-- name: CreateProjectHistoryEntry :one

INSERT INTO kanban_project_history (
    project_id, user_id, action, entity_title, entity_link,
    entity_type, entity_id, card_id, payload
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, project_id, user_id, action, entity_type, entity_id, card_id, entity_title, entity_link, payload, created_at
`

type CreateProjectHistoryEntryParams struct {
	ProjectID   int64       `json:"project_id"`
	UserID      pgtype.Int8 `json:"user_id"`
	Action      string      `json:"action"`
	EntityTitle string      `json:"entity_title"`
	EntityLink  string      `json:"entity_link"`
	EntityType  string      `json:"entity_type"`
	EntityID    int64       `json:"entity_id"`
	CardID      pgtype.Int8 `json:"card_id"`
	Payload     []byte      `json:"payload"`
}

// ==============================
// PROJECT HISTORY
// ==============================
func (q *Queries) CreateProjectHistoryEntry(ctx context.Context, arg CreateProjectHistoryEntryParams) (KanbanProjectHistory, error) {
	row := q.db.QueryRow(ctx, createProjectHistoryEntry,
		arg.ProjectID,
		arg.UserID,
		arg.Action,
		arg.EntityTitle,
		arg.EntityLink,
		arg.EntityType,
		arg.EntityID,
		arg.CardID,
		arg.Payload,
	)
	var i KanbanProjectHistory
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UserID,
		&i.Action,
		&i.EntityType,
		&i.EntityID,
		&i.CardID,
		&i.EntityTitle,
		&i.EntityLink,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAttachment = `-- name: DeleteAttachment :exec
UPDATE kanban_attachment
SET deleted_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) DeleteAttachment(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteAttachment, id)
	return err
}

const deleteBoard = `-- name: DeleteBoard :exec
UPDATE kanban_board
SET deleted_at = CURRENT_TIMESTAMP
WHERE id = $1
`

func (q *Queries) DeleteBoard(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteBoard, id)
	return err
}

const deleteCard = `-- name: DeleteCard :execrows
UPDATE kanban_card
SET deleted_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP
WHERE deleted_at IS NULL AND (id = $1 OR parent_id = $1)
`

// Ноль строк — карточки нет или она уже удалена: вызывающий отвечает 404.
func (q *Queries) DeleteCard(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCard, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteColumn = `-- name: DeleteColumn :exec
UPDATE kanban_column
SET deleted_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) DeleteColumn(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteColumn, id)
	return err
}

const deleteComment = `-- name: DeleteComment :exec
UPDATE kanban_card_comment
SET deleted_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) DeleteComment(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteComment, id)
	return err
}

const deleteLabel = `-- name: DeleteLabel :exec
UPDATE kanban_label
SET deleted_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) DeleteLabel(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteLabel, id)
	return err
}

const deleteProject = `-- name: DeleteProject :exec
UPDATE kanban_project
SET deleted_at = CURRENT_TIMESTAMP
WHERE id = $1
`

func (q *Queries) DeleteProject(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteProject, id)
	return err
}

const deleteProjectFolder = `-- name: DeleteProjectFolder :exec
DELETE FROM kanban_project_user_folder
WHERE id = $1
`

func (q *Queries) DeleteProjectFolder(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteProjectFolder, id)
	return err
}

const deleteProjectHistoryEntry = `-- name: DeleteProjectHistoryEntry :exec
DELETE FROM kanban_project_history
WHERE id = $1
`

func (q *Queries) DeleteProjectHistoryEntry(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteProjectHistoryEntry, id)
	return err
}

const deleteProjectMembersExcept = `-- name: DeleteProjectMembersExcept :exec
DELETE FROM kanban_project_user
WHERE kanban_project_id = $1 AND NOT (user_id = ANY($2::bigint[]))
`

type DeleteProjectMembersExceptParams struct {
	KanbanProjectID int64   `json:"kanban_project_id"`
	KeepUserIds     []int64 `json:"keep_user_ids"`
}

func (q *Queries) DeleteProjectMembersExcept(ctx context.Context, arg DeleteProjectMembersExceptParams) error {
	_, err := q.db.Exec(ctx, deleteProjectMembersExcept, arg.KanbanProjectID, arg.KeepUserIds)
	return err
}

const duplicateCard = `-- name: DuplicateCard :many
WITH copy AS (
    INSERT INTO kanban_card (title, description, position, due_date, priority, column_id, created_by_id, border_color)
    SELECT title, description, $1::float8, due_date, priority,
           $2::bigint, $3::bigint, border_color
    FROM kanban_card
    WHERE id = $4::bigint AND deleted_at IS NULL
    RETURNING id, title, description, position, due_date, priority, is_archived, archived_at, archived_by_id, completed_at, completed_by_id, column_id, created_by_id, border_color, created_at, updated_at, deleted_at, parent_id
), children AS (
    INSERT INTO kanban_card (title, position, parent_id, created_by_id)
    SELECT src.title, src.position, copy.id, $3::bigint
    FROM kanban_card src CROSS JOIN copy
    WHERE src.parent_id = $4::bigint AND src.deleted_at IS NULL
    RETURNING id, title, description, position, due_date, priority, is_archived, archived_at, archived_by_id, completed_at, completed_by_id, column_id, created_by_id, border_color, created_at, updated_at, deleted_at, parent_id
)
SELECT id, title, description, position, due_date, priority, is_archived, archived_at, archived_by_id, completed_at, completed_by_id, column_id, created_by_id, border_color, created_at, updated_at, deleted_at, parent_id FROM copy
UNION ALL
SELECT id, title, description, position, due_date, priority, is_archived, archived_at, archived_by_id, completed_at, completed_by_id, column_id, created_by_id, border_color, created_at, updated_at, deleted_at, parent_id FROM children
ORDER BY parent_id NULLS FIRST, position
`

type DuplicateCardParams struct {
	Position    float64     `json:"position"`
	ColumnID    int64       `json:"column_id"`
	CreatedByID pgtype.Int8 `json:"created_by_id"`
	SourceID    int64       `json:"source_id"`
}

type DuplicateCardRow struct {
	ID            int64              `json:"id"`
	Title         string             `json:"title"`
	Description   pgtype.Text        `json:"description"`
	Position      float64            `json:"position"`
	DueDate       pgtype.Timestamptz `json:"due_date"`
	Priority      pgtype.Text        `json:"priority"`
	IsArchived    bool               `json:"is_archived"`
	ArchivedAt    pgtype.Timestamptz `json:"archived_at"`
	ArchivedByID  pgtype.Int8        `json:"archived_by_id"`
	CompletedAt   pgtype.Timestamptz `json:"completed_at"`
	CompletedByID pgtype.Int8        `json:"completed_by_id"`
	ColumnID      pgtype.Int8        `json:"column_id"`
	CreatedByID   pgtype.Int8        `json:"created_by_id"`
	BorderColor   pgtype.Text        `json:"border_color"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
	ParentID      pgtype.Int8        `json:"parent_id"`
}

// Копия карточки с подзадачами одним оператором — он атомарен сам по себе.
// Переносятся заголовок, описание, срок, приоритет и цвет, у подзадач —
// заголовок и порядок. Метки, исполнители, выполнение, комментарии и вложения
// остаются у оригинала; автор копии и её подзадач — тот, кто копирует.
// Первая строка — сама копия, дальше её подзадачи по порядку.
func (q *Queries) DuplicateCard(ctx context.Context, arg DuplicateCardParams) ([]DuplicateCardRow, error) {
	rows, err := q.db.Query(ctx, duplicateCard,
		arg.Position,
		arg.ColumnID,
		arg.CreatedByID,
		arg.SourceID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DuplicateCardRow{}
	for rows.Next() {
		var i DuplicateCardRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Position,
			&i.DueDate,
			&i.Priority,
			&i.IsArchived,
			&i.ArchivedAt,
			&i.ArchivedByID,
			&i.CompletedAt,
			&i.CompletedByID,
			&i.ColumnID,
			&i.CreatedByID,
			&i.BorderColor,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ParentID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllProjects = `-- name: GetAllProjects :many
SELECT id, name, description, owner_id, created_by_id, created_at, updated_at, deleted_at FROM kanban_project
WHERE deleted_at IS NULL
ORDER BY id DESC
`

func (q *Queries) GetAllProjects(ctx context.Context) ([]KanbanProject, error) {
	rows, err := q.db.Query(ctx, getAllProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KanbanProject{}
	for rows.Next() {
		var i KanbanProject
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.OwnerID,
			&i.CreatedByID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAttachment = `-- name: GetAttachment :one

SELECT id, filename, storage_key, content_type, size_bytes, card_id, context, author_id, created_at, deleted_at FROM kanban_attachment
WHERE id = $1 AND deleted_at IS NULL LIMIT 1
`

// ==============================
// ATTACHMENTS
// ==============================
func (q *Queries) GetAttachment(ctx context.Context, id int64) (KanbanAttachment, error) {
	row := q.db.QueryRow(ctx, getAttachment, id)
	var i KanbanAttachment
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.StorageKey,
		&i.ContentType,
		&i.SizeBytes,
		&i.CardID,
		&i.Context,
		&i.AuthorID,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAttachmentsByCard = `-- name: GetAttachmentsByCard :many
SELECT id, filename, storage_key, content_type, size_bytes, card_id, context, author_id, created_at, deleted_at FROM kanban_attachment
WHERE card_id = $1 AND context = $2 AND deleted_at IS NULL
ORDER BY created_at ASC
`

type GetAttachmentsByCardParams struct {
	CardID  int64  `json:"card_id"`
	Context string `json:"context"`
}

func (q *Queries) GetAttachmentsByCard(ctx context.Context, arg GetAttachmentsByCardParams) ([]KanbanAttachment, error) {
	rows, err := q.db.Query(ctx, getAttachmentsByCard, arg.CardID, arg.Context)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KanbanAttachment{}
	for rows.Next() {
		var i KanbanAttachment
		if err := rows.Scan(
			&i.ID,
			&i.Filename,
			&i.StorageKey,
			&i.ContentType,
			&i.SizeBytes,
			&i.CardID,
			&i.Context,
			&i.AuthorID,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBoard = `-- name: GetBoard :one

SELECT id, title, position, kanban_project_id, created_by_id, created_at, updated_at, deleted_at, done_column_id FROM kanban_board
WHERE id = $1 AND deleted_at IS NULL LIMIT 1
`

// ==============================
// BOARDS
// ==============================
func (q *Queries) GetBoard(ctx context.Context, id int64) (KanbanBoard, error) {
	row := q.db.QueryRow(ctx, getBoard, id)
	var i KanbanBoard
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Position,
		&i.KanbanProjectID,
		&i.CreatedByID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DoneColumnID,
	)
	return i, err
}

const getBoardsByProject = `-- name: GetBoardsByProject :many
SELECT id, title, position, kanban_project_id, created_by_id, created_at, updated_at, deleted_at, done_column_id FROM kanban_board
WHERE kanban_project_id = $1 AND deleted_at IS NULL
ORDER BY position ASC
`

func (q *Queries) GetBoardsByProject(ctx context.Context, kanbanProjectID int64) ([]KanbanBoard, error) {
	rows, err := q.db.Query(ctx, getBoardsByProject, kanbanProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KanbanBoard{}
	for rows.Next() {
		var i KanbanBoard
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Position,
			&i.KanbanProjectID,
			&i.CreatedByID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DoneColumnID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCard = `-- name: GetCard :one

SELECT id, title, description, position, due_date, priority, is_archived, archived_at, archived_by_id, completed_at, completed_by_id, column_id, created_by_id, border_color, created_at, updated_at, deleted_at, parent_id FROM kanban_card
WHERE id = $1 AND deleted_at IS NULL LIMIT 1
`

// ==============================
// CARDS
// ==============================
func (q *Queries) GetCard(ctx context.Context, id int64) (KanbanCard, error) {
	row := q.db.QueryRow(ctx, getCard, id)
	var i KanbanCard
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Position,
		&i.DueDate,
		&i.Priority,
		&i.IsArchived,
		&i.ArchivedAt,
		&i.ArchivedByID,
		&i.CompletedAt,
		&i.CompletedByID,
		&i.ColumnID,
		&i.CreatedByID,
		&i.BorderColor,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ParentID,
	)
	return i, err
}

const getCardAssignees = `-- name: GetCardAssignees :many

SELECT user_id FROM kanban_card_assignee
WHERE card_id = $1
`

// ==============================
// CARD ASSIGNEES
// ==============================
func (q *Queries) GetCardAssignees(ctx context.Context, cardID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, getCardAssignees, cardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var user_id int64
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCardAssigneesByCardIDs = `-- name: GetCardAssigneesByCardIDs :many
SELECT card_id, user_id FROM kanban_card_assignee
WHERE card_id = ANY($1::bigint[])
`

func (q *Queries) GetCardAssigneesByCardIDs(ctx context.Context, dollar_1 []int64) ([]KanbanCardAssignee, error) {
	rows, err := q.db.Query(ctx, getCardAssigneesByCardIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KanbanCardAssignee{}
	for rows.Next() {
		var i KanbanCardAssignee
		if err := rows.Scan(&i.CardID, &i.UserID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCardContext = `-- name: GetCardContext :one
SELECT
    b.kanban_project_id,
    b.id AS board_id,
    b.title AS board_title,
    col.title AS column_title,
    p.owner_id,
    p.deleted_at AS project_deleted_at,
    pu.role AS member_role,
    card.parent_id AS parent_id,
    card.is_archived,
    card.title AS card_title,
    col.id AS column_id,
    card.position,
    card.completed_at,
    b.done_column_id
FROM kanban_card card
LEFT JOIN kanban_card parent ON parent.id = card.parent_id
JOIN kanban_column col ON col.id = COALESCE(card.column_id, parent.column_id)
JOIN kanban_board b ON col.board_id = b.id
JOIN kanban_project p ON b.kanban_project_id = p.id
LEFT JOIN kanban_project_user pu
       ON pu.kanban_project_id = p.id AND pu.user_id = $2
WHERE card.id = $1
`

type GetCardContextParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

type GetCardContextRow struct {
	KanbanProjectID  int64              `json:"kanban_project_id"`
	BoardID          int64              `json:"board_id"`
	BoardTitle       string             `json:"board_title"`
	ColumnTitle      string             `json:"column_title"`
	OwnerID          int64              `json:"owner_id"`
	ProjectDeletedAt pgtype.Timestamptz `json:"project_deleted_at"`
	MemberRole       pgtype.Text        `json:"member_role"`
	ParentID         pgtype.Int8        `json:"parent_id"`
	IsArchived       bool               `json:"is_archived"`
	CardTitle        string             `json:"card_title"`
	ColumnID         int64              `json:"column_id"`
	Position         float64            `json:"position"`
	CompletedAt      pgtype.Timestamptz `json:"completed_at"`
	DoneColumnID     pgtype.Int8        `json:"done_column_id"`
}

// Всё, что нужно для проверки прав и для шапки карточки, одним запросом:
// проект, доска с названием, заголовок колонки, владелец и роль вызывающего.
// Джойны те же, что в GetProjectIDByCard, плюс проект — все по первичным
// ключам, членство — по уникальному (kanban_project_id, user_id).
// Роль берём LEFT JOIN'ом, а не отдельным GetProjectMember: членства может не
// быть вовсе (владелец, чужой пользователь), и NULL здесь — это отказ, который
// разбирает resolveRole.
// Название доски нужно уведомлениям: без него они ходили за ним в GetBoard.
// deleted_at проекта не фильтруем в WHERE, а возвращаем: иначе «карточки нет»
// и «проект удалён» схлопнутся в одну ошибку и фронт получит не тот код.
func (q *Queries) GetCardContext(ctx context.Context, arg GetCardContextParams) (GetCardContextRow, error) {
	row := q.db.QueryRow(ctx, getCardContext, arg.ID, arg.UserID)
	var i GetCardContextRow
	err := row.Scan(
		&i.KanbanProjectID,
		&i.BoardID,
		&i.BoardTitle,
		&i.ColumnTitle,
		&i.OwnerID,
		&i.ProjectDeletedAt,
		&i.MemberRole,
		&i.ParentID,
		&i.IsArchived,
		&i.CardTitle,
		&i.ColumnID,
		&i.Position,
		&i.CompletedAt,
		&i.DoneColumnID,
	)
	return i, err
}

const getCardIDsByLabel = `-- name: GetCardIDsByLabel :many
SELECT cl.kanban_card_id FROM kanban_card_label cl
JOIN kanban_card c ON c.id = cl.kanban_card_id
WHERE cl.kanban_label_id = $1 AND c.deleted_at IS NULL
`

func (q *Queries) GetCardIDsByLabel(ctx context.Context, kanbanLabelID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, getCardIDsByLabel, kanbanLabelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var kanban_card_id int64
		if err := rows.Scan(&kanban_card_id); err != nil {
			return nil, err
		}
		items = append(items, kanban_card_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCardLabels = `-- name: GetCardLabels :many

SELECT cl.kanban_label_id FROM kanban_card_label cl
JOIN kanban_label l ON l.id = cl.kanban_label_id
WHERE cl.kanban_card_id = $1 AND l.deleted_at IS NULL
`

// ==============================
// CARD LABELS
// ==============================
func (q *Queries) GetCardLabels(ctx context.Context, kanbanCardID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, getCardLabels, kanbanCardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var kanban_label_id int64
		if err := rows.Scan(&kanban_label_id); err != nil {
			return nil, err
		}
		items = append(items, kanban_label_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCardLabelsByCardIDs = `-- name: GetCardLabelsByCardIDs :many
SELECT cl.kanban_card_id, cl.kanban_label_id FROM kanban_card_label cl
JOIN kanban_label l ON l.id = cl.kanban_label_id
WHERE cl.kanban_card_id = ANY($1::bigint[]) AND l.deleted_at IS NULL
`

func (q *Queries) GetCardLabelsByCardIDs(ctx context.Context, dollar_1 []int64) ([]KanbanCardLabel, error) {
	rows, err := q.db.Query(ctx, getCardLabelsByCardIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KanbanCardLabel{}
	for rows.Next() {
		var i KanbanCardLabel
		if err := rows.Scan(&i.KanbanCardID, &i.KanbanLabelID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCardReadMark = `-- name: GetCardReadMark :one
SELECT COALESCE(MAX(up_to_comment_id), 0)::bigint AS last_read_comment_id
FROM kanban_card_read
WHERE card_id = $1 AND user_id = $2
`

type GetCardReadMarkParams struct {
	CardID int64 `json:"card_id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) GetCardReadMark(ctx context.Context, arg GetCardReadMarkParams) (int64, error) {
	row := q.db.QueryRow(ctx, getCardReadMark, arg.CardID, arg.UserID)
	var last_read_comment_id int64
	err := row.Scan(&last_read_comment_id)
	return last_read_comment_id, err
}

const getCardsByBoard = `-- name: GetCardsByBoard :many
SELECT c.id, c.title, c.description, c.position, c.due_date, c.priority, c.is_archived, c.archived_at, c.archived_by_id, c.completed_at, c.completed_by_id, c.column_id, c.created_by_id, c.border_color, c.created_at, c.updated_at, c.deleted_at, c.parent_id FROM kanban_card c
JOIN kanban_column col ON col.id = c.column_id
WHERE col.board_id = $1 AND c.parent_id IS NULL AND c.is_archived = FALSE AND c.deleted_at IS NULL AND col.deleted_at IS NULL
ORDER BY col.position ASC, c.position ASC
`

func (q *Queries) GetCardsByBoard(ctx context.Context, boardID int64) ([]KanbanCard, error) {
	rows, err := q.db.Query(ctx, getCardsByBoard, boardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KanbanCard{}
	for rows.Next() {
		var i KanbanCard
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Position,
			&i.DueDate,
			&i.Priority,
			&i.IsArchived,
			&i.ArchivedAt,
			&i.ArchivedByID,
			&i.CompletedAt,
			&i.CompletedByID,
			&i.ColumnID,
			&i.CreatedByID,
			&i.BorderColor,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ParentID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChatAttachmentCountsByCardIDs = `-- name: GetChatAttachmentCountsByCardIDs :many
SELECT card_id, COUNT(*) AS count
FROM kanban_attachment
WHERE card_id = ANY($1::bigint[]) AND context = 'chat' AND deleted_at IS NULL
GROUP BY card_id
`

type GetChatAttachmentCountsByCardIDsRow struct {
	CardID int64 `json:"card_id"`
	Count  int64 `json:"count"`
}

func (q *Queries) GetChatAttachmentCountsByCardIDs(ctx context.Context, dollar_1 []int64) ([]GetChatAttachmentCountsByCardIDsRow, error) {
	rows, err := q.db.Query(ctx, getChatAttachmentCountsByCardIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetChatAttachmentCountsByCardIDsRow{}
	for rows.Next() {
		var i GetChatAttachmentCountsByCardIDsRow
		if err := rows.Scan(&i.CardID, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChildCards = `-- name: GetChildCards :many
SELECT id, title, description, position, due_date, priority, is_archived, archived_at, archived_by_id, completed_at, completed_by_id, column_id, created_by_id, border_color, created_at, updated_at, deleted_at, parent_id FROM kanban_card
WHERE parent_id = $1 AND deleted_at IS NULL
ORDER BY position ASC
`

func (q *Queries) GetChildCards(ctx context.Context, parentID pgtype.Int8) ([]KanbanCard, error) {
	rows, err := q.db.Query(ctx, getChildCards, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KanbanCard{}
	for rows.Next() {
		var i KanbanCard
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Position,
			&i.DueDate,
			&i.Priority,
			&i.IsArchived,
			&i.ArchivedAt,
			&i.ArchivedByID,
			&i.CompletedAt,
			&i.CompletedByID,
			&i.ColumnID,
			&i.CreatedByID,
			&i.BorderColor,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ParentID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChildCountsByParentIDs = `-- name: GetChildCountsByParentIDs :many
SELECT parent_id,
       COUNT(*) AS total,
       COUNT(*) FILTER (WHERE completed_at IS NOT NULL) AS done
FROM kanban_card
WHERE parent_id = ANY($1::bigint[]) AND deleted_at IS NULL
GROUP BY parent_id
`

type GetChildCountsByParentIDsRow struct {
	ParentID pgtype.Int8 `json:"parent_id"`
	Total    int64       `json:"total"`
	Done     int64       `json:"done"`
}

func (q *Queries) GetChildCountsByParentIDs(ctx context.Context, dollar_1 []int64) ([]GetChildCountsByParentIDsRow, error) {
	rows, err := q.db.Query(ctx, getChildCountsByParentIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetChildCountsByParentIDsRow{}
	for rows.Next() {
		var i GetChildCountsByParentIDsRow
		if err := rows.Scan(&i.ParentID, &i.Total, &i.Done); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChildStats = `-- name: GetChildStats :one
SELECT COUNT(*)::bigint AS total,
       COALESCE(MAX(position), 0)::double precision AS max_position
FROM kanban_card
WHERE parent_id = $1 AND deleted_at IS NULL
`

type GetChildStatsRow struct {
	Total       int64   `json:"total"`
	MaxPosition float64 `json:"max_position"`
}

// Счётчик и хвостовая позиция для создания подзадачи: всё, что нужно,
// без вычитывания самих детей и их исполнителей.
func (q *Queries) GetChildStats(ctx context.Context, parentID pgtype.Int8) (GetChildStatsRow, error) {
	row := q.db.QueryRow(ctx, getChildStats, parentID)
	var i GetChildStatsRow
	err := row.Scan(&i.Total, &i.MaxPosition)
	return i, err
}

const getColumn = `-- name: GetColumn :one

SELECT id, title, header_color, position, board_id, deleted_at FROM kanban_column
WHERE id = $1 AND deleted_at IS NULL LIMIT 1
`

// ==============================
// COLUMNS
// ==============================
func (q *Queries) GetColumn(ctx context.Context, id int64) (KanbanColumn, error) {
	row := q.db.QueryRow(ctx, getColumn, id)
	var i KanbanColumn
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.HeaderColor,
		&i.Position,
		&i.BoardID,
		&i.DeletedAt,
	)
	return i, err
}

const getColumnContext = `-- name: GetColumnContext :one
SELECT
    b.kanban_project_id,
    b.id AS board_id,
    b.title AS board_title,
    col.title AS column_title,
    p.owner_id,
    p.deleted_at AS project_deleted_at,
    pu.role AS member_role,
    COALESCE((
        SELECT MIN(c.position) / 2 FROM kanban_card c
        WHERE c.column_id = col.id AND c.parent_id IS NULL
          AND c.is_archived = FALSE AND c.deleted_at IS NULL
    ), 65536)::float8 AS prepend_position
FROM kanban_column col
JOIN kanban_board b ON b.id = col.board_id
JOIN kanban_project p ON p.id = b.kanban_project_id
LEFT JOIN kanban_project_user pu
       ON pu.kanban_project_id = p.id AND pu.user_id = $2
WHERE col.id = $1 AND col.deleted_at IS NULL
`

type GetColumnContextParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

type GetColumnContextRow struct {
	KanbanProjectID  int64              `json:"kanban_project_id"`
	BoardID          int64              `json:"board_id"`
	BoardTitle       string             `json:"board_title"`
	ColumnTitle      string             `json:"column_title"`
	OwnerID          int64              `json:"owner_id"`
	ProjectDeletedAt pgtype.Timestamptz `json:"project_deleted_at"`
	MemberRole       pgtype.Text        `json:"member_role"`
	PrependPosition  float64            `json:"prepend_position"`
}

// То же, что GetCardContext, но от колонки — всё, что нужно созданию карточки,
// одним запросом: права, доска с названием, заголовок колонки и позиция над
// верхней карточкой (FIRST/2; пустая колонка — 65536). Удалённая колонка —
// «не найдена», удалённый проект возвращается, а не фильтруется, по той же
// причине, что в GetCardContext.
func (q *Queries) GetColumnContext(ctx context.Context, arg GetColumnContextParams) (GetColumnContextRow, error) {
	row := q.db.QueryRow(ctx, getColumnContext, arg.ID, arg.UserID)
	var i GetColumnContextRow
	err := row.Scan(
		&i.KanbanProjectID,
		&i.BoardID,
		&i.BoardTitle,
		&i.ColumnTitle,
		&i.OwnerID,
		&i.ProjectDeletedAt,
		&i.MemberRole,
		&i.PrependPosition,
	)
	return i, err
}

const getColumnPrependTarget = `-- name: GetColumnPrependTarget :one
SELECT col.title, col.board_id, b.kanban_project_id,
       COALESCE((
           SELECT MIN(c.position) / 2 FROM kanban_card c
           WHERE c.column_id = col.id AND c.parent_id IS NULL
             AND c.is_archived = FALSE AND c.deleted_at IS NULL
       ), 65536)::float8 AS target_position
FROM kanban_column col
JOIN kanban_board b ON b.id = col.board_id
WHERE col.id = $1 AND col.deleted_at IS NULL
`

type GetColumnPrependTargetRow struct {
	Title           string  `json:"title"`
	BoardID         int64   `json:"board_id"`
	KanbanProjectID int64   `json:"kanban_project_id"`
	TargetPosition  float64 `json:"target_position"`
}

// Колонка, в которую карточка встаёт наверх: автоперенос в «Готово» и копия.
// Позиция — над верхней карточкой (FIRST/2, как при создании; пустая колонка —
// 65536): раньше ради одного MIN читалась вся колонка с исполнителями и метками.
// Проект — чтобы копия не ушла в чужой; удалённая колонка — «не найдена»
// (удаление колонки не сбрасывает done_column_id доски).
func (q *Queries) GetColumnPrependTarget(ctx context.Context, id int64) (GetColumnPrependTargetRow, error) {
	row := q.db.QueryRow(ctx, getColumnPrependTarget, id)
	var i GetColumnPrependTargetRow
	err := row.Scan(
		&i.Title,
		&i.BoardID,
		&i.KanbanProjectID,
		&i.TargetPosition,
	)
	return i, err
}

const getColumnsByBoard = `-- name: GetColumnsByBoard :many
SELECT id, title, header_color, position, board_id, deleted_at FROM kanban_column
WHERE board_id = $1 AND deleted_at IS NULL
ORDER BY position ASC
`

func (q *Queries) GetColumnsByBoard(ctx context.Context, boardID int64) ([]KanbanColumn, error) {
	rows, err := q.db.Query(ctx, getColumnsByBoard, boardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KanbanColumn{}
	for rows.Next() {
		var i KanbanColumn
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.HeaderColor,
			&i.Position,
			&i.BoardID,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getComment = `-- name: GetComment :one

SELECT id, body, card_id, author_id, created_at, updated_at, deleted_at FROM kanban_card_comment
WHERE id = $1 AND deleted_at IS NULL LIMIT 1
`

// ==============================
// COMMENTS
// ==============================
func (q *Queries) GetComment(ctx context.Context, id int64) (KanbanCardComment, error) {
	row := q.db.QueryRow(ctx, getComment, id)
	var i KanbanCardComment
	err := row.Scan(
		&i.ID,
		&i.Body,
		&i.CardID,
		&i.AuthorID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getCommentCountsByCardIDs = `-- name: GetCommentCountsByCardIDs :many
SELECT card_id, COUNT(*) AS count
FROM kanban_card_comment
WHERE card_id = ANY($1::bigint[]) AND deleted_at IS NULL
GROUP BY card_id
`

type GetCommentCountsByCardIDsRow struct {
	CardID int64 `json:"card_id"`
	Count  int64 `json:"count"`
}

func (q *Queries) GetCommentCountsByCardIDs(ctx context.Context, dollar_1 []int64) ([]GetCommentCountsByCardIDsRow, error) {
	rows, err := q.db.Query(ctx, getCommentCountsByCardIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCommentCountsByCardIDsRow{}
	for rows.Next() {
		var i GetCommentCountsByCardIDsRow
		if err := rows.Scan(&i.CardID, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCommentReaders = `-- name: GetCommentReaders :many
SELECT DISTINCT ON (user_id) user_id, read_at
FROM kanban_card_read
WHERE card_id = $1 AND up_to_comment_id >= $2
ORDER BY user_id, up_to_comment_id
`

type GetCommentReadersParams struct {
	CardID        int64 `json:"card_id"`
	UpToCommentID int64 `json:"up_to_comment_id"`
}

type GetCommentReadersRow struct {
	UserID int64              `json:"user_id"`
	ReadAt pgtype.Timestamptz `json:"read_at"`
}

// Самый ранний заход, накрывший комментарий, — это и есть момент, когда
// человек его увидел. Порядок берётся из первичного ключа, без сортировки.
func (q *Queries) GetCommentReaders(ctx context.Context, arg GetCommentReadersParams) ([]GetCommentReadersRow, error) {
	rows, err := q.db.Query(ctx, getCommentReaders, arg.CardID, arg.UpToCommentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCommentReadersRow{}
	for rows.Next() {
		var i GetCommentReadersRow
		if err := rows.Scan(&i.UserID, &i.ReadAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCommentsByCard = `-- name: GetCommentsByCard :many
SELECT id, body, card_id, author_id, created_at, updated_at, deleted_at FROM kanban_card_comment
WHERE card_id = $1 AND deleted_at IS NULL
ORDER BY created_at ASC
`

func (q *Queries) GetCommentsByCard(ctx context.Context, cardID int64) ([]KanbanCardComment, error) {
	rows, err := q.db.Query(ctx, getCommentsByCard, cardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KanbanCardComment{}
	for rows.Next() {
		var i KanbanCardComment
		if err := rows.Scan(
			&i.ID,
			&i.Body,
			&i.CardID,
			&i.AuthorID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLabel = `-- name: GetLabel :one

SELECT id, name, color, board_id, deleted_at FROM kanban_label
WHERE id = $1 AND deleted_at IS NULL LIMIT 1
`

// ==============================
// LABELS
// ==============================
func (q *Queries) GetLabel(ctx context.Context, id int64) (KanbanLabel, error) {
	row := q.db.QueryRow(ctx, getLabel, id)
	var i KanbanLabel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.BoardID,
		&i.DeletedAt,
	)
	return i, err
}

const getLabelsByBoard = `-- name: GetLabelsByBoard :many
SELECT id, name, color, board_id, deleted_at FROM kanban_label
WHERE board_id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetLabelsByBoard(ctx context.Context, boardID int64) ([]KanbanLabel, error) {
	rows, err := q.db.Query(ctx, getLabelsByBoard, boardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KanbanLabel{}
	for rows.Next() {
		var i KanbanLabel
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Color,
			&i.BoardID,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLastProjectHistoryByUser = `-- name: GetLastProjectHistoryByUser :one
SELECT id, project_id, user_id, action, entity_type, entity_id, card_id, entity_title, entity_link, payload, created_at FROM kanban_project_history
WHERE project_id = $1 AND user_id = $2
ORDER BY id DESC
LIMIT 1
`

type GetLastProjectHistoryByUserParams struct {
	ProjectID int64       `json:"project_id"`
	UserID    pgtype.Int8 `json:"user_id"`
}

func (q *Queries) GetLastProjectHistoryByUser(ctx context.Context, arg GetLastProjectHistoryByUserParams) (KanbanProjectHistory, error) {
	row := q.db.QueryRow(ctx, getLastProjectHistoryByUser, arg.ProjectID, arg.UserID)
	var i KanbanProjectHistory
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UserID,
		&i.Action,
		&i.EntityType,
		&i.EntityID,
		&i.CardID,
		&i.EntityTitle,
		&i.EntityLink,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const getProject = `-- name: GetProject :one
SELECT id, name, description, owner_id, created_by_id, created_at, updated_at, deleted_at FROM kanban_project
WHERE id = $1 AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetProject(ctx context.Context, id int64) (KanbanProject, error) {
	row := q.db.QueryRow(ctx, getProject, id)
	var i KanbanProject
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.OwnerID,
		&i.CreatedByID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getProjectAssignee = `-- name: GetProjectAssignee :one
SELECT u.id, u.login, u.lastname, u.firstname, u.patronymic, u.avatar_name,
       (pu.user_id IS NOT NULL)::bool AS is_member
FROM users u
LEFT JOIN kanban_project_user pu
       ON pu.kanban_project_id = $1 AND pu.user_id = u.id
WHERE u.id = $2
`

type GetProjectAssigneeParams struct {
	ProjectID int64 `json:"project_id"`
	UserID    int64 `json:"user_id"`
}

type GetProjectAssigneeRow struct {
	ID         int64       `json:"id"`
	Login      string      `json:"login"`
	Lastname   string      `json:"lastname"`
	Firstname  string      `json:"firstname"`
	Patronymic pgtype.Text `json:"patronymic"`
	AvatarName pgtype.Text `json:"avatar_name"`
	IsMember   bool        `json:"is_member"`
}

// Кандидат в исполнители вместе с членством в проекте — одним запросом вместо
// GetUsersByIDs + GetProject + GetProjectMember. Владельца в kanban_project_user
// может не быть: его отличает вызывающий по owner_id из контекста карточки.
func (q *Queries) GetProjectAssignee(ctx context.Context, arg GetProjectAssigneeParams) (GetProjectAssigneeRow, error) {
	row := q.db.QueryRow(ctx, getProjectAssignee, arg.ProjectID, arg.UserID)
	var i GetProjectAssigneeRow
	err := row.Scan(
		&i.ID,
		&i.Login,
		&i.Lastname,
		&i.Firstname,
		&i.Patronymic,
		&i.AvatarName,
		&i.IsMember,
	)
	return i, err
}

const getProjectFolders = `-- name: GetProjectFolders :many

SELECT id, name, user_id, position, created_at, updated_at FROM kanban_project_user_folder
WHERE user_id = $1 ORDER BY position ASC
`

// ==============================
// PROJECT FOLDERS
// ==============================
func (q *Queries) GetProjectFolders(ctx context.Context, userID int64) ([]KanbanProjectUserFolder, error) {
	rows, err := q.db.Query(ctx, getProjectFolders, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KanbanProjectUserFolder{}
	for rows.Next() {
		var i KanbanProjectUserFolder
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.UserID,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProjectHistoryEntry = `-- name: GetProjectHistoryEntry :one
SELECT id, project_id, user_id, action, entity_type, entity_id, card_id, entity_title, entity_link, payload, created_at FROM kanban_project_history
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetProjectHistoryEntry(ctx context.Context, id int64) (KanbanProjectHistory, error) {
	row := q.db.QueryRow(ctx, getProjectHistoryEntry, id)
	var i KanbanProjectHistory
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UserID,
		&i.Action,
		&i.EntityType,
		&i.EntityID,
		&i.CardID,
		&i.EntityTitle,
		&i.EntityLink,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const getProjectIDByCard = `-- name: GetProjectIDByCard :one
SELECT b.kanban_project_id FROM kanban_card card
LEFT JOIN kanban_card parent ON parent.id = card.parent_id
JOIN kanban_column c ON c.id = COALESCE(card.column_id, parent.column_id)
JOIN kanban_board b ON c.board_id = b.id
WHERE card.id = $1
`

func (q *Queries) GetProjectIDByCard(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, getProjectIDByCard, id)
	var kanban_project_id int64
	err := row.Scan(&kanban_project_id)
	return kanban_project_id, err
}

const getProjectIDByLabel = `-- name: GetProjectIDByLabel :one
SELECT b.kanban_project_id as project_id
FROM kanban_label l
JOIN kanban_board b ON l.board_id = b.id
WHERE l.id = $1
`

func (q *Queries) GetProjectIDByLabel(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, getProjectIDByLabel, id)
	var project_id int64
	err := row.Scan(&project_id)
	return project_id, err
}

const getProjectMember = `-- name: GetProjectMember :one
SELECT id, kanban_project_id, user_id, role, folder_id, position FROM kanban_project_user
WHERE kanban_project_id = $1 AND user_id = $2
`

type GetProjectMemberParams struct {
	KanbanProjectID int64 `json:"kanban_project_id"`
	UserID          int64 `json:"user_id"`
}

func (q *Queries) GetProjectMember(ctx context.Context, arg GetProjectMemberParams) (KanbanProjectUser, error) {
	row := q.db.QueryRow(ctx, getProjectMember, arg.KanbanProjectID, arg.UserID)
	var i KanbanProjectUser
	err := row.Scan(
		&i.ID,
		&i.KanbanProjectID,
		&i.UserID,
		&i.Role,
		&i.FolderID,
		&i.Position,
	)
	return i, err
}

const getProjectMembers = `-- name: GetProjectMembers :many

SELECT id, kanban_project_id, user_id, role, folder_id, position FROM kanban_project_user
WHERE kanban_project_id = $1
`

// ==============================
// PROJECT MEMBERS
// ==============================
func (q *Queries) GetProjectMembers(ctx context.Context, kanbanProjectID int64) ([]KanbanProjectUser, error) {
	rows, err := q.db.Query(ctx, getProjectMembers, kanbanProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KanbanProjectUser{}
	for rows.Next() {
		var i KanbanProjectUser
		if err := rows.Scan(
			&i.ID,
			&i.KanbanProjectID,
			&i.UserID,
			&i.Role,
			&i.FolderID,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hasCardsByColumn = `-- name: HasCardsByColumn :one
SELECT EXISTS(
    SELECT 1 FROM kanban_card
    WHERE column_id = $1 AND parent_id IS NULL AND deleted_at IS NULL
)
`

func (q *Queries) HasCardsByColumn(ctx context.Context, columnID pgtype.Int8) (bool, error) {
	row := q.db.QueryRow(ctx, hasCardsByColumn, columnID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const hasColumnsByBoard = `-- name: HasColumnsByBoard :one
SELECT EXISTS(
    SELECT 1 FROM kanban_column WHERE board_id = $1 AND deleted_at IS NULL
)
`

func (q *Queries) HasColumnsByBoard(ctx context.Context, boardID int64) (bool, error) {
	row := q.db.QueryRow(ctx, hasColumnsByBoard, boardID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const hasForeignNewerHistoryOverlap = `-- name: HasForeignNewerHistoryOverlap :one
SELECT EXISTS(
    SELECT 1 FROM kanban_project_history
    WHERE project_id = $1
      AND id > $2
      AND user_id IS DISTINCT FROM $3
      AND entity_type = $4
      AND entity_id = $5
)
`

type HasForeignNewerHistoryOverlapParams struct {
	ProjectID  int64       `json:"project_id"`
	AfterID    int64       `json:"after_id"`
	UserID     pgtype.Int8 `json:"user_id"`
	EntityType string      `json:"entity_type"`
	EntityID   int64       `json:"entity_id"`
}

func (q *Queries) HasForeignNewerHistoryOverlap(ctx context.Context, arg HasForeignNewerHistoryOverlapParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasForeignNewerHistoryOverlap,
		arg.ProjectID,
		arg.AfterID,
		arg.UserID,
		arg.EntityType,
		arg.EntityID,
	)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listProjectHistory = `-- name: ListProjectHistory :many
SELECT
    j.id,
    j.project_id,
    j.user_id,
    j.action,
    j.entity_title,
    j.entity_link,
    j.payload,
    j.created_at,
    (j.entity_type = 'card' AND j.card_id IS NOT NULL AND j.entity_id <> j.card_id) AS is_child,
    u.lastname,
    u.firstname,
    u.patronymic
FROM kanban_project_history j
LEFT JOIN users u ON u.id = j.user_id
WHERE j.project_id = $1
  AND ($2::bigint = 0 OR j.card_id = $2)
  AND ($3::bigint = 0 OR j.user_id = $3)
  AND ($4::text = '' OR j.entity_title ILIKE '%' || $4 || '%' ESCAPE '\')
  AND ($5::bigint = 0 OR j.id < $5)
ORDER BY j.id DESC
LIMIT $6
`

type ListProjectHistoryParams struct {
	ProjectID  int64  `json:"project_id"`
	CardID     int64  `json:"card_id"`
	UserID     int64  `json:"user_id"`
	TitleQuery string `json:"title_query"`
	Cursor     int64  `json:"cursor"`
	PageLimit  int32  `json:"page_limit"`
}

type ListProjectHistoryRow struct {
	ID          int64              `json:"id"`
	ProjectID   int64              `json:"project_id"`
	UserID      pgtype.Int8        `json:"user_id"`
	Action      string             `json:"action"`
	EntityTitle string             `json:"entity_title"`
	EntityLink  string             `json:"entity_link"`
	Payload     []byte             `json:"payload"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	IsChild     pgtype.Bool        `json:"is_child"`
	Lastname    pgtype.Text        `json:"lastname"`
	Firstname   pgtype.Text        `json:"firstname"`
	Patronymic  pgtype.Text        `json:"patronymic"`
}

func (q *Queries) ListProjectHistory(ctx context.Context, arg ListProjectHistoryParams) ([]ListProjectHistoryRow, error) {
	rows, err := q.db.Query(ctx, listProjectHistory,
		arg.ProjectID,
		arg.CardID,
		arg.UserID,
		arg.TitleQuery,
		arg.Cursor,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectHistoryRow{}
	for rows.Next() {
		var i ListProjectHistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.UserID,
			&i.Action,
			&i.EntityTitle,
			&i.EntityLink,
			&i.Payload,
			&i.CreatedAt,
			&i.IsChild,
			&i.Lastname,
			&i.Firstname,
			&i.Patronymic,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskCollaborants = `-- name: ListTaskCollaborants :many


WITH visible AS (
    SELECT p.id, p.owner_id
    FROM kanban_project p
    WHERE p.deleted_at IS NULL
      AND (
          p.owner_id = $1
          OR EXISTS (
              SELECT 1 FROM kanban_project_user pu
              WHERE pu.kanban_project_id = p.id
                AND pu.user_id = $1
          )
      )
),
ids AS (
    SELECT visible.owner_id AS user_id FROM visible
    UNION
    SELECT pu.user_id
    FROM kanban_project_user pu
    INNER JOIN visible ON visible.id = pu.kanban_project_id
)
SELECT COUNT(*) OVER ()::bigint AS total_count,
       u.id, u.login, u.lastname, u.firstname, u.patronymic, u.avatar_name
FROM ids
INNER JOIN users u ON u.id = ids.user_id
WHERE u.deleted_at IS NULL
  AND u.id <> $1
  AND (
      $2::text = ''
      OR u.lastname ILIKE '%' || $2 || '%' ESCAPE '\'
      OR u.firstname ILIKE '%' || $2 || '%' ESCAPE '\'
      OR u.login ILIKE '%' || $2 || '%' ESCAPE '\'
      OR COALESCE(u.patronymic, '') ILIKE '%' || $2 || '%' ESCAPE '\'
  )
ORDER BY u.lastname ASC, u.firstname ASC, u.id ASC
LIMIT $4
OFFSET $3
`

type ListTaskCollaborantsParams struct {
	ViewerID   int64  `json:"viewer_id"`
	NameQuery  string `json:"name_query"`
	PageOffset int32  `json:"page_offset"`
	PageLimit  int32  `json:"page_limit"`
}

type ListTaskCollaborantsRow struct {
	TotalCount int64       `json:"total_count"`
	ID         int64       `json:"id"`
	Login      string      `json:"login"`
	Lastname   string      `json:"lastname"`
	Firstname  string      `json:"firstname"`
	Patronymic pgtype.Text `json:"patronymic"`
	AvatarName pgtype.Text `json:"avatar_name"`
}

// Список задач (ListTasks) собирается динамически в card_repository.go:
// фильтров полтора десятка, и статический запрос с `$n = ” OR ...` не давал
// планировщику взять индекс ни по одному из них.
// ==============================
// TASK COLLABORANTS
// ==============================
func (q *Queries) ListTaskCollaborants(ctx context.Context, arg ListTaskCollaborantsParams) ([]ListTaskCollaborantsRow, error) {
	rows, err := q.db.Query(ctx, listTaskCollaborants,
		arg.ViewerID,
		arg.NameQuery,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTaskCollaborantsRow{}
	for rows.Next() {
		var i ListTaskCollaborantsRow
		if err := rows.Scan(
			&i.TotalCount,
			&i.ID,
			&i.Login,
			&i.Lastname,
			&i.Firstname,
			&i.Patronymic,
			&i.AvatarName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markCommentsRead = `-- name: MarkCommentsRead :exec

INSERT INTO kanban_card_read (card_id, user_id, up_to_comment_id)
SELECT $1::bigint, $2::bigint, $3::bigint
WHERE EXISTS (
    SELECT 1 FROM kanban_card_comment
    WHERE id = $3
      AND card_id = $1
      AND deleted_at IS NULL
)
AND $3 > COALESCE((
    SELECT MAX(up_to_comment_id) FROM kanban_card_read
    WHERE card_id = $1 AND user_id = $2
), 0)
ON CONFLICT DO NOTHING
`

type MarkCommentsReadParams struct {
	CardID        int64 `json:"card_id"`
	UserID        int64 `json:"user_id"`
	UpToCommentID int64 `json:"up_to_comment_id"`
}

// ==============================
// COMMENT READ MARKS
// ==============================
// Проверка «знак вырос» живёт внутри запроса: иначе между чтением максимума
// и вставкой влезает соседняя вкладка того же пользователя. Устаревшее или
// меньшее число просто не вставится, ON CONFLICT добивает точные дубли.
// EXISTS обязателен: без него клиент присылает id из будущего и помечает
// прочитанными комментарии, которых ещё нет.
func (q *Queries) MarkCommentsRead(ctx context.Context, arg MarkCommentsReadParams) error {
	_, err := q.db.Exec(ctx, markCommentsRead, arg.CardID, arg.UserID, arg.UpToCommentID)
	return err
}

const rebalanceColumnCards = `-- name: RebalanceColumnCards :exec
WITH ranked AS (
  SELECT id, ROW_NUMBER() OVER(ORDER BY position ASC, id ASC) as rn
  FROM kanban_card
  WHERE kanban_card.column_id = $1 AND kanban_card.parent_id IS NULL AND kanban_card.is_archived = FALSE AND kanban_card.deleted_at IS NULL
)
UPDATE kanban_card
SET position = ranked.rn * 65536.0
FROM ranked
WHERE kanban_card.id = ranked.id
`

func (q *Queries) RebalanceColumnCards(ctx context.Context, columnID pgtype.Int8) error {
	_, err := q.db.Exec(ctx, rebalanceColumnCards, columnID)
	return err
}

const removeCardAssignee = `-- name: RemoveCardAssignee :exec
DELETE FROM kanban_card_assignee
WHERE card_id = $1 AND user_id = $2
`

type RemoveCardAssigneeParams struct {
	CardID int64 `json:"card_id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) RemoveCardAssignee(ctx context.Context, arg RemoveCardAssigneeParams) error {
	_, err := q.db.Exec(ctx, removeCardAssignee, arg.CardID, arg.UserID)
	return err
}

const removeCardLabel = `-- name: RemoveCardLabel :exec
DELETE FROM kanban_card_label
WHERE kanban_card_id = $1 AND kanban_label_id = $2
`

type RemoveCardLabelParams struct {
	KanbanCardID  int64 `json:"kanban_card_id"`
	KanbanLabelID int64 `json:"kanban_label_id"`
}

func (q *Queries) RemoveCardLabel(ctx context.Context, arg RemoveCardLabelParams) error {
	_, err := q.db.Exec(ctx, removeCardLabel, arg.KanbanCardID, arg.KanbanLabelID)
	return err
}

const removeProjectMember = `-- name: RemoveProjectMember :exec
DELETE FROM kanban_project_user
WHERE kanban_project_id = $1 AND user_id = $2
`

type RemoveProjectMemberParams struct {
	KanbanProjectID int64 `json:"kanban_project_id"`
	UserID          int64 `json:"user_id"`
}

func (q *Queries) RemoveProjectMember(ctx context.Context, arg RemoveProjectMemberParams) error {
	_, err := q.db.Exec(ctx, removeProjectMember, arg.KanbanProjectID, arg.UserID)
	return err
}

const replaceCardAssignees = `-- name: ReplaceCardAssignees :many
WITH old AS (
    SELECT user_id FROM kanban_card_assignee WHERE card_id = $1::bigint
), removed AS (
    DELETE FROM kanban_card_assignee
    WHERE card_id = $1::bigint AND user_id <> ALL($2::bigint[])
), added AS (
    INSERT INTO kanban_card_assignee (card_id, user_id)
    SELECT $1::bigint, unnest($2::bigint[])
    ON CONFLICT DO NOTHING
)
SELECT user_id FROM old
`

type ReplaceCardAssigneesParams struct {
	CardID  int64   `json:"card_id"`
	UserIds []int64 `json:"user_ids"`
}

// Замена исполнителей одним оператором — он атомарен сам по себе, транзакция
// не нужна. Все части видят состояние до оператора: old — прежний состав для
// истории, DELETE не трогает остающихся, INSERT добавляет новых.
func (q *Queries) ReplaceCardAssignees(ctx context.Context, arg ReplaceCardAssigneesParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, replaceCardAssignees, arg.CardID, arg.UserIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var user_id int64
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreAttachment = `-- name: RestoreAttachment :exec
UPDATE kanban_attachment
SET deleted_at = NULL
WHERE id = $1
`

func (q *Queries) RestoreAttachment(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, restoreAttachment, id)
	return err
}

const restoreBoard = `-- name: RestoreBoard :exec
UPDATE kanban_board
SET deleted_at = NULL, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

func (q *Queries) RestoreBoard(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, restoreBoard, id)
	return err
}

const restoreCard = `-- name: RestoreCard :exec
UPDATE kanban_card c
SET deleted_at = NULL, updated_at = CURRENT_TIMESTAMP
FROM kanban_card p
WHERE p.id = $1
  AND (c.id = p.id OR (c.parent_id = p.id AND c.deleted_at = p.deleted_at))
`

// Возвращаем только тех детей, которых удалили вместе с родителем: DeleteCard
// ставит им один и тот же CURRENT_TIMESTAMP (время транзакции). Дети, удалённые
// раньше и отдельно, к этой отмене отношения не имеют и остаются удалёнными.
// Сторона FROM видит снимок до UPDATE, то есть p.deleted_at читается старым.
func (q *Queries) RestoreCard(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, restoreCard, id)
	return err
}

const restoreColumn = `-- name: RestoreColumn :exec
UPDATE kanban_column
SET deleted_at = NULL
WHERE id = $1
`

func (q *Queries) RestoreColumn(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, restoreColumn, id)
	return err
}

const restoreComment = `-- name: RestoreComment :exec
UPDATE kanban_card_comment
SET deleted_at = NULL
WHERE id = $1
`

func (q *Queries) RestoreComment(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, restoreComment, id)
	return err
}

const restoreLabel = `-- name: RestoreLabel :exec
UPDATE kanban_label
SET deleted_at = NULL
WHERE id = $1
`

func (q *Queries) RestoreLabel(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, restoreLabel, id)
	return err
}

const restoreProject = `-- name: RestoreProject :exec
UPDATE kanban_project
SET deleted_at = NULL, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

func (q *Queries) RestoreProject(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, restoreProject, id)
	return err
}

const setCardArchived = `-- name: SetCardArchived :one
UPDATE kanban_card
SET is_archived = $2, archived_at = $3, archived_by_id = $4, updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
RETURNING title
`

type SetCardArchivedParams struct {
	ID           int64              `json:"id"`
	IsArchived   bool               `json:"is_archived"`
	ArchivedAt   pgtype.Timestamptz `json:"archived_at"`
	ArchivedByID pgtype.Int8        `json:"archived_by_id"`
}

// Только поля архива, а не вся строка, как в UpdateCard: иначе архивация
// затрёт заголовок или описание, которые в этот момент правит кто-то другой.
// Заголовок нужен истории — отдельное чтение карточки ради него не требуется.
func (q *Queries) SetCardArchived(ctx context.Context, arg SetCardArchivedParams) (string, error) {
	row := q.db.QueryRow(ctx, setCardArchived,
		arg.ID,
		arg.IsArchived,
		arg.ArchivedAt,
		arg.ArchivedByID,
	)
	var title string
	err := row.Scan(&title)
	return title, err
}

const setCardCompleted = `-- name: SetCardCompleted :one
UPDATE kanban_card
SET completed_at = $2, completed_by_id = $3, updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
RETURNING updated_at
`

type SetCardCompletedParams struct {
	ID            int64              `json:"id"`
	CompletedAt   pgtype.Timestamptz `json:"completed_at"`
	CompletedByID pgtype.Int8        `json:"completed_by_id"`
}

// Только поля выполнения — по той же причине, что SetCardArchived: перезапись
// всей строки откатывала перемещение, случившееся между чтением и записью.
func (q *Queries) SetCardCompleted(ctx context.Context, arg SetCardCompletedParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, setCardCompleted, arg.ID, arg.CompletedAt, arg.CompletedByID)
	var updated_at pgtype.Timestamptz
	err := row.Scan(&updated_at)
	return updated_at, err
}

const setDoneColumnID = `-- name: SetDoneColumnID :exec
UPDATE kanban_board
SET done_column_id = $1, updated_at = CURRENT_TIMESTAMP
WHERE id = $2 AND deleted_at IS NULL
`

type SetDoneColumnIDParams struct {
	DoneColumnID pgtype.Int8 `json:"done_column_id"`
	ID           int64       `json:"id"`
}

func (q *Queries) SetDoneColumnID(ctx context.Context, arg SetDoneColumnIDParams) error {
	_, err := q.db.Exec(ctx, setDoneColumnID, arg.DoneColumnID, arg.ID)
	return err
}

const updateBoard = `-- name: UpdateBoard :one
UPDATE kanban_board
SET title = $1, position = $2, updated_at = CURRENT_TIMESTAMP
WHERE id = $3 AND deleted_at IS NULL
RETURNING id, title, position, kanban_project_id, created_by_id, created_at, updated_at, deleted_at, done_column_id
`

type UpdateBoardParams struct {
	Title    string  `json:"title"`
	Position float64 `json:"position"`
	ID       int64   `json:"id"`
}

func (q *Queries) UpdateBoard(ctx context.Context, arg UpdateBoardParams) (KanbanBoard, error) {
	row := q.db.QueryRow(ctx, updateBoard, arg.Title, arg.Position, arg.ID)
	var i KanbanBoard
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Position,
		&i.KanbanProjectID,
		&i.CreatedByID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DoneColumnID,
	)
	return i, err
}

const updateCard = `-- name: UpdateCard :one
UPDATE kanban_card
SET title = $1, description = $2, position = $3, due_date = $4, priority = $5, is_archived = $6, archived_at = $7, archived_by_id = $8, completed_at = $9, completed_by_id = $10, column_id = $11, parent_id = $12, border_color = $13, updated_at = CURRENT_TIMESTAMP
WHERE id = $14
RETURNING id, title, description, position, due_date, priority, is_archived, archived_at, archived_by_id, completed_at, completed_by_id, column_id, created_by_id, border_color, created_at, updated_at, deleted_at, parent_id
`

type UpdateCardParams struct {
	Title         string             `json:"title"`
	Description   pgtype.Text        `json:"description"`
	Position      float64            `json:"position"`
	DueDate       pgtype.Timestamptz `json:"due_date"`
	Priority      pgtype.Text        `json:"priority"`
	IsArchived    bool               `json:"is_archived"`
	ArchivedAt    pgtype.Timestamptz `json:"archived_at"`
	ArchivedByID  pgtype.Int8        `json:"archived_by_id"`
	CompletedAt   pgtype.Timestamptz `json:"completed_at"`
	CompletedByID pgtype.Int8        `json:"completed_by_id"`
	ColumnID      pgtype.Int8        `json:"column_id"`
	ParentID      pgtype.Int8        `json:"parent_id"`
	BorderColor   pgtype.Text        `json:"border_color"`
	ID            int64              `json:"id"`
}

func (q *Queries) UpdateCard(ctx context.Context, arg UpdateCardParams) (KanbanCard, error) {
	row := q.db.QueryRow(ctx, updateCard,
		arg.Title,
		arg.Description,
		arg.Position,
		arg.DueDate,
		arg.Priority,
		arg.IsArchived,
		arg.ArchivedAt,
		arg.ArchivedByID,
		arg.CompletedAt,
		arg.CompletedByID,
		arg.ColumnID,
		arg.ParentID,
		arg.BorderColor,
		arg.ID,
	)
	var i KanbanCard
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Position,
		&i.DueDate,
		&i.Priority,
		&i.IsArchived,
		&i.ArchivedAt,
		&i.ArchivedByID,
		&i.CompletedAt,
		&i.CompletedByID,
		&i.ColumnID,
		&i.CreatedByID,
		&i.BorderColor,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ParentID,
	)
	return i, err
}

const updateCardFields = `-- name: UpdateCardFields :one
UPDATE kanban_card
SET title = $2, description = $3, due_date = $4, priority = $5, border_color = $6, updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, title, description, position, due_date, priority, is_archived, archived_at, archived_by_id, completed_at, completed_by_id, column_id, created_by_id, border_color, created_at, updated_at, deleted_at, parent_id
`

type UpdateCardFieldsParams struct {
	ID          int64              `json:"id"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	DueDate     pgtype.Timestamptz `json:"due_date"`
	Priority    pgtype.Text        `json:"priority"`
	BorderColor pgtype.Text        `json:"border_color"`
}

// Только то, что редактируется в карточке. Выполнение, архив, колонку и позицию
// правка не пишет: иначе откатит завершение или перенос, случившиеся между
// чтением карточки и записью. Строка целиком нужна ответу и realtime.
func (q *Queries) UpdateCardFields(ctx context.Context, arg UpdateCardFieldsParams) (KanbanCard, error) {
	row := q.db.QueryRow(ctx, updateCardFields,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.DueDate,
		arg.Priority,
		arg.BorderColor,
	)
	var i KanbanCard
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Position,
		&i.DueDate,
		&i.Priority,
		&i.IsArchived,
		&i.ArchivedAt,
		&i.ArchivedByID,
		&i.CompletedAt,
		&i.CompletedByID,
		&i.ColumnID,
		&i.CreatedByID,
		&i.BorderColor,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ParentID,
	)
	return i, err
}

const updateCardPosition = `-- name: UpdateCardPosition :one
UPDATE kanban_card c
SET position = $2, updated_at = CURRENT_TIMESTAMP
FROM kanban_card old
WHERE c.id = $1 AND old.id = c.id AND c.deleted_at IS NULL
RETURNING c.id, c.title, c.position, c.updated_at, old.position AS old_position
`

type UpdateCardPositionParams struct {
	ID       int64   `json:"id"`
	Position float64 `json:"position"`
}

type UpdateCardPositionRow struct {
	ID          int64              `json:"id"`
	Title       string             `json:"title"`
	Position    float64            `json:"position"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	OldPosition float64            `json:"old_position"`
}

// Перестановка не должна затирать заголовок, который в этот же момент правит
// кто-то другой, — поэтому узкий UPDATE, а не перезапись всей строки.
// Старая позиция нужна истории как Before, и она же приезжает из FROM —
// отдельное чтение карточки ради одного числа не требуется.
func (q *Queries) UpdateCardPosition(ctx context.Context, arg UpdateCardPositionParams) (UpdateCardPositionRow, error) {
	row := q.db.QueryRow(ctx, updateCardPosition, arg.ID, arg.Position)
	var i UpdateCardPositionRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Position,
		&i.UpdatedAt,
		&i.OldPosition,
	)
	return i, err
}

const updateColumn = `-- name: UpdateColumn :one
UPDATE kanban_column
SET title = $1, header_color = $2, position = $3
WHERE id = $4 AND deleted_at IS NULL
RETURNING id, title, header_color, position, board_id, deleted_at
`

type UpdateColumnParams struct {
	Title       string  `json:"title"`
	HeaderColor string  `json:"header_color"`
	Position    float64 `json:"position"`
	ID          int64   `json:"id"`
}

func (q *Queries) UpdateColumn(ctx context.Context, arg UpdateColumnParams) (KanbanColumn, error) {
	row := q.db.QueryRow(ctx, updateColumn,
		arg.Title,
		arg.HeaderColor,
		arg.Position,
		arg.ID,
	)
	var i KanbanColumn
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.HeaderColor,
		&i.Position,
		&i.BoardID,
		&i.DeletedAt,
	)
	return i, err
}

const updateComment = `-- name: UpdateComment :one
UPDATE kanban_card_comment
SET body = $1, updated_at = CURRENT_TIMESTAMP
WHERE id = $2 AND deleted_at IS NULL
RETURNING id, body, card_id, author_id, created_at, updated_at, deleted_at
`

type UpdateCommentParams struct {
	Body string `json:"body"`
	ID   int64  `json:"id"`
}

func (q *Queries) UpdateComment(ctx context.Context, arg UpdateCommentParams) (KanbanCardComment, error) {
	row := q.db.QueryRow(ctx, updateComment, arg.Body, arg.ID)
	var i KanbanCardComment
	err := row.Scan(
		&i.ID,
		&i.Body,
		&i.CardID,
		&i.AuthorID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateProject = `-- name: UpdateProject :one
UPDATE kanban_project
SET name = $1, description = $2, updated_at = CURRENT_TIMESTAMP
WHERE id = $3 AND deleted_at IS NULL
RETURNING id, name, description, owner_id, created_by_id, created_at, updated_at, deleted_at
`

type UpdateProjectParams struct {
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	ID          int64       `json:"id"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (KanbanProject, error) {
	row := q.db.QueryRow(ctx, updateProject, arg.Name, arg.Description, arg.ID)
	var i KanbanProject
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.OwnerID,
		&i.CreatedByID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateProjectFolder = `-- name: UpdateProjectFolder :one
UPDATE kanban_project_user_folder
SET name = $1, position = $2, updated_at = CURRENT_TIMESTAMP
WHERE id = $3
RETURNING id, name, user_id, position, created_at, updated_at
`

type UpdateProjectFolderParams struct {
	Name     string  `json:"name"`
	Position float64 `json:"position"`
	ID       int64   `json:"id"`
}

func (q *Queries) UpdateProjectFolder(ctx context.Context, arg UpdateProjectFolderParams) (KanbanProjectUserFolder, error) {
	row := q.db.QueryRow(ctx, updateProjectFolder, arg.Name, arg.Position, arg.ID)
	var i KanbanProjectUserFolder
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.UserID,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProjectMemberRole = `-- name: UpdateProjectMemberRole :exec
UPDATE kanban_project_user
SET role = $3
WHERE kanban_project_id = $1 AND user_id = $2
`

type UpdateProjectMemberRoleParams struct {
	KanbanProjectID int64  `json:"kanban_project_id"`
	UserID          int64  `json:"user_id"`
	Role            string `json:"role"`
}

func (q *Queries) UpdateProjectMemberRole(ctx context.Context, arg UpdateProjectMemberRoleParams) error {
	_, err := q.db.Exec(ctx, updateProjectMemberRole, arg.KanbanProjectID, arg.UserID, arg.Role)
	return err
}
