// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addCardAssignee = `-- name: AddCardAssignee :exec
INSERT INTO kanban_card_assignee (card_id, user_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddCardAssigneeParams struct {
	CardID int64 `json:"card_id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) AddCardAssignee(ctx context.Context, arg AddCardAssigneeParams) error {
	_, err := q.db.Exec(ctx, addCardAssignee, arg.CardID, arg.UserID)
	return err
}

const addCardLabel = `-- name: AddCardLabel :exec
INSERT INTO kanban_card_label (kanban_card_id, kanban_label_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddCardLabelParams struct {
	KanbanCardID  int64 `json:"kanban_card_id"`
	KanbanLabelID int64 `json:"kanban_label_id"`
}

func (q *Queries) AddCardLabel(ctx context.Context, arg AddCardLabelParams) error {
	_, err := q.db.Exec(ctx, addCardLabel, arg.KanbanCardID, arg.KanbanLabelID)
	return err
}

const addProjectMember = `-- name: AddProjectMember :exec
INSERT INTO kanban_project_user (kanban_project_id, user_id, role, folder_id, position)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (kanban_project_id, user_id) DO UPDATE 
SET role = EXCLUDED.role, folder_id = EXCLUDED.folder_id, position = EXCLUDED.position
`

type AddProjectMemberParams struct {
	KanbanProjectID int64       `json:"kanban_project_id"`
	UserID          int64       `json:"user_id"`
	Role            string      `json:"role"`
	FolderID        pgtype.Int8 `json:"folder_id"`
	Position        float64     `json:"position"`
}

func (q *Queries) AddProjectMember(ctx context.Context, arg AddProjectMemberParams) error {
	_, err := q.db.Exec(ctx, addProjectMember,
		arg.KanbanProjectID,
		arg.UserID,
		arg.Role,
		arg.FolderID,
		arg.Position,
	)
	return err
}

const clearCardAssignees = `-- name: ClearCardAssignees :exec
DELETE FROM kanban_card_assignee
WHERE card_id = $1
`

func (q *Queries) ClearCardAssignees(ctx context.Context, cardID int64) error {
	_, err := q.db.Exec(ctx, clearCardAssignees, cardID)
	return err
}

const createActivity = `-- name: CreateActivity :one
INSERT INTO kanban_card_activity (type, card_id, user_id, old_value, new_value)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, card_id, user_id, type, old_value, new_value, created_at
`

type CreateActivityParams struct {
	Type     string      `json:"type"`
	CardID   int64       `json:"card_id"`
	UserID   pgtype.Int8 `json:"user_id"`
	OldValue pgtype.Text `json:"old_value"`
	NewValue pgtype.Text `json:"new_value"`
}

func (q *Queries) CreateActivity(ctx context.Context, arg CreateActivityParams) (KanbanCardActivity, error) {
	row := q.db.QueryRow(ctx, createActivity,
		arg.Type,
		arg.CardID,
		arg.UserID,
		arg.OldValue,
		arg.NewValue,
	)
	var i KanbanCardActivity
	err := row.Scan(
		&i.ID,
		&i.CardID,
		&i.UserID,
		&i.Type,
		&i.OldValue,
		&i.NewValue,
		&i.CreatedAt,
	)
	return i, err
}

const createAttachment = `-- name: CreateAttachment :one
INSERT INTO kanban_attachment (filename, storage_key, content_type, size_bytes, context, card_id, author_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, filename, storage_key, content_type, size_bytes, card_id, context, author_id, created_at
`

type CreateAttachmentParams struct {
	Filename    string      `json:"filename"`
	StorageKey  string      `json:"storage_key"`
	ContentType string      `json:"content_type"`
	SizeBytes   int64       `json:"size_bytes"`
	Context     string      `json:"context"`
	CardID      int64       `json:"card_id"`
	AuthorID    pgtype.Int8 `json:"author_id"`
}

func (q *Queries) CreateAttachment(ctx context.Context, arg CreateAttachmentParams) (KanbanAttachment, error) {
	row := q.db.QueryRow(ctx, createAttachment,
		arg.Filename,
		arg.StorageKey,
		arg.ContentType,
		arg.SizeBytes,
		arg.Context,
		arg.CardID,
		arg.AuthorID,
	)
	var i KanbanAttachment
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.StorageKey,
		&i.ContentType,
		&i.SizeBytes,
		&i.CardID,
		&i.Context,
		&i.AuthorID,
		&i.CreatedAt,
	)
	return i, err
}

const createBoard = `-- name: CreateBoard :one
INSERT INTO kanban_board (title, position, kanban_project_id, created_by_id)
VALUES ($1, $2, $3, $4)
RETURNING id, title, position, kanban_project_id, created_by_id, created_at, updated_at, deleted_at
`

type CreateBoardParams struct {
	Title           string  `json:"title"`
	Position        float64 `json:"position"`
	KanbanProjectID int64   `json:"kanban_project_id"`
	CreatedByID     int64   `json:"created_by_id"`
}

func (q *Queries) CreateBoard(ctx context.Context, arg CreateBoardParams) (KanbanBoard, error) {
	row := q.db.QueryRow(ctx, createBoard,
		arg.Title,
		arg.Position,
		arg.KanbanProjectID,
		arg.CreatedByID,
	)
	var i KanbanBoard
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Position,
		&i.KanbanProjectID,
		&i.CreatedByID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createCard = `-- name: CreateCard :one
INSERT INTO kanban_card (title, description, position, due_date, priority, column_id, created_by_id, border_color)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, title, description, position, due_date, priority, is_archived, archived_at, archived_by_id, completed_at, completed_by_id, column_id, created_by_id, border_color, created_at, updated_at
`

type CreateCardParams struct {
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	Position    float64            `json:"position"`
	DueDate     pgtype.Timestamptz `json:"due_date"`
	Priority    pgtype.Text        `json:"priority"`
	ColumnID    int64              `json:"column_id"`
	CreatedByID pgtype.Int8        `json:"created_by_id"`
	BorderColor pgtype.Text        `json:"border_color"`
}

func (q *Queries) CreateCard(ctx context.Context, arg CreateCardParams) (KanbanCard, error) {
	row := q.db.QueryRow(ctx, createCard,
		arg.Title,
		arg.Description,
		arg.Position,
		arg.DueDate,
		arg.Priority,
		arg.ColumnID,
		arg.CreatedByID,
		arg.BorderColor,
	)
	var i KanbanCard
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Position,
		&i.DueDate,
		&i.Priority,
		&i.IsArchived,
		&i.ArchivedAt,
		&i.ArchivedByID,
		&i.CompletedAt,
		&i.CompletedByID,
		&i.ColumnID,
		&i.CreatedByID,
		&i.BorderColor,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createColumn = `-- name: CreateColumn :one
INSERT INTO kanban_column (title, header_color, position, board_id)
VALUES ($1, $2, $3, $4)
RETURNING id, title, header_color, position, board_id
`

type CreateColumnParams struct {
	Title       string  `json:"title"`
	HeaderColor string  `json:"header_color"`
	Position    float64 `json:"position"`
	BoardID     int64   `json:"board_id"`
}

func (q *Queries) CreateColumn(ctx context.Context, arg CreateColumnParams) (KanbanColumn, error) {
	row := q.db.QueryRow(ctx, createColumn,
		arg.Title,
		arg.HeaderColor,
		arg.Position,
		arg.BoardID,
	)
	var i KanbanColumn
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.HeaderColor,
		&i.Position,
		&i.BoardID,
	)
	return i, err
}

const createComment = `-- name: CreateComment :one
INSERT INTO kanban_card_comment (body, card_id, author_id)
VALUES ($1, $2, $3)
RETURNING id, body, card_id, author_id, created_at, updated_at
`

type CreateCommentParams struct {
	Body     string `json:"body"`
	CardID   int64  `json:"card_id"`
	AuthorID int64  `json:"author_id"`
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (KanbanCardComment, error) {
	row := q.db.QueryRow(ctx, createComment, arg.Body, arg.CardID, arg.AuthorID)
	var i KanbanCardComment
	err := row.Scan(
		&i.ID,
		&i.Body,
		&i.CardID,
		&i.AuthorID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createLabel = `-- name: CreateLabel :one
INSERT INTO kanban_label (name, color, board_id)
VALUES ($1, $2, $3)
RETURNING id, name, color, board_id
`

type CreateLabelParams struct {
	Name    string `json:"name"`
	Color   string `json:"color"`
	BoardID int64  `json:"board_id"`
}

func (q *Queries) CreateLabel(ctx context.Context, arg CreateLabelParams) (KanbanLabel, error) {
	row := q.db.QueryRow(ctx, createLabel, arg.Name, arg.Color, arg.BoardID)
	var i KanbanLabel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.BoardID,
	)
	return i, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO kanban_project (name, description, owner_id, created_by_id)
VALUES ($1, $2, $3, $4)
RETURNING id, name, description, owner_id, created_by_id, created_at, updated_at, deleted_at
`

type CreateProjectParams struct {
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	OwnerID     int64       `json:"owner_id"`
	CreatedByID pgtype.Int8 `json:"created_by_id"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (KanbanProject, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.Name,
		arg.Description,
		arg.OwnerID,
		arg.CreatedByID,
	)
	var i KanbanProject
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.OwnerID,
		&i.CreatedByID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createProjectFolder = `-- name: CreateProjectFolder :one
INSERT INTO kanban_project_user_folder (name, user_id, position)
VALUES ($1, $2, $3)
RETURNING id, name, user_id, position, created_at, updated_at
`

type CreateProjectFolderParams struct {
	Name     string  `json:"name"`
	UserID   int64   `json:"user_id"`
	Position float64 `json:"position"`
}

func (q *Queries) CreateProjectFolder(ctx context.Context, arg CreateProjectFolderParams) (KanbanProjectUserFolder, error) {
	row := q.db.QueryRow(ctx, createProjectFolder, arg.Name, arg.UserID, arg.Position)
	var i KanbanProjectUserFolder
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.UserID,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSubtask = `-- name: CreateSubtask :one
INSERT INTO kanban_card_subtask (title, status, position, card_id, user_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, title, status, position, card_id, user_id
`

type CreateSubtaskParams struct {
	Title    string      `json:"title"`
	Status   string      `json:"status"`
	Position float64     `json:"position"`
	CardID   int64       `json:"card_id"`
	UserID   pgtype.Int8 `json:"user_id"`
}

func (q *Queries) CreateSubtask(ctx context.Context, arg CreateSubtaskParams) (KanbanCardSubtask, error) {
	row := q.db.QueryRow(ctx, createSubtask,
		arg.Title,
		arg.Status,
		arg.Position,
		arg.CardID,
		arg.UserID,
	)
	var i KanbanCardSubtask
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Status,
		&i.Position,
		&i.CardID,
		&i.UserID,
	)
	return i, err
}

const deleteAttachment = `-- name: DeleteAttachment :exec
DELETE FROM kanban_attachment
WHERE id = $1
`

func (q *Queries) DeleteAttachment(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteAttachment, id)
	return err
}

const deleteBoard = `-- name: DeleteBoard :exec
UPDATE kanban_board
SET deleted_at = CURRENT_TIMESTAMP
WHERE id = $1
`

func (q *Queries) DeleteBoard(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteBoard, id)
	return err
}

const deleteCard = `-- name: DeleteCard :exec
DELETE FROM kanban_card
WHERE id = $1
`

func (q *Queries) DeleteCard(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteCard, id)
	return err
}

const deleteColumn = `-- name: DeleteColumn :exec
DELETE FROM kanban_column
WHERE id = $1
`

func (q *Queries) DeleteColumn(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteColumn, id)
	return err
}

const deleteComment = `-- name: DeleteComment :exec
DELETE FROM kanban_card_comment
WHERE id = $1
`

func (q *Queries) DeleteComment(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteComment, id)
	return err
}

const deleteLabel = `-- name: DeleteLabel :exec
DELETE FROM kanban_label
WHERE id = $1
`

func (q *Queries) DeleteLabel(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteLabel, id)
	return err
}

const deleteProject = `-- name: DeleteProject :exec
UPDATE kanban_project
SET deleted_at = CURRENT_TIMESTAMP
WHERE id = $1
`

func (q *Queries) DeleteProject(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteProject, id)
	return err
}

const deleteProjectFolder = `-- name: DeleteProjectFolder :exec
DELETE FROM kanban_project_user_folder
WHERE id = $1
`

func (q *Queries) DeleteProjectFolder(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteProjectFolder, id)
	return err
}

const deleteSubtask = `-- name: DeleteSubtask :exec
DELETE FROM kanban_card_subtask
WHERE id = $1
`

func (q *Queries) DeleteSubtask(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteSubtask, id)
	return err
}

const getActivitiesByCard = `-- name: GetActivitiesByCard :many

SELECT id, card_id, user_id, type, old_value, new_value, created_at FROM kanban_card_activity
WHERE card_id = $1
ORDER BY created_at DESC
`

// ==============================
// ACTIVITY
// ==============================
func (q *Queries) GetActivitiesByCard(ctx context.Context, cardID int64) ([]KanbanCardActivity, error) {
	rows, err := q.db.Query(ctx, getActivitiesByCard, cardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KanbanCardActivity{}
	for rows.Next() {
		var i KanbanCardActivity
		if err := rows.Scan(
			&i.ID,
			&i.CardID,
			&i.UserID,
			&i.Type,
			&i.OldValue,
			&i.NewValue,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllProjects = `-- name: GetAllProjects :many
SELECT id, name, description, owner_id, created_by_id, created_at, updated_at, deleted_at FROM kanban_project
WHERE deleted_at IS NULL
ORDER BY id DESC
`

func (q *Queries) GetAllProjects(ctx context.Context) ([]KanbanProject, error) {
	rows, err := q.db.Query(ctx, getAllProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KanbanProject{}
	for rows.Next() {
		var i KanbanProject
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.OwnerID,
			&i.CreatedByID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAssignedCardsClosed = `-- name: GetAssignedCardsClosed :many
SELECT
    p.id            AS project_id,
    p.name          AS project_name,
    b.id            AS board_id,
    b.title         AS board_title,
    b.position      AS board_position,
    col.id          AS column_id,
    col.title       AS column_title,
    col.position    AS column_position,
    c.id            AS card_id,
    c.title         AS card_title,
    c.priority      AS card_priority,
    c.due_date      AS card_due_date,
    c.border_color  AS card_border_color,
    c.position      AS card_position
FROM kanban_card_assignee ca
JOIN kanban_card    c   ON c.id  = ca.card_id
JOIN kanban_column  col ON col.id = c.column_id
JOIN kanban_board   b   ON b.id  = col.board_id
JOIN kanban_project p   ON p.id  = b.kanban_project_id
WHERE ca.user_id = $1
  AND c.completed_at IS NOT NULL
  AND c.is_archived = FALSE
  AND b.deleted_at IS NULL
  AND p.deleted_at IS NULL
  AND (
      p.owner_id = $1
      OR EXISTS (
          SELECT 1 FROM kanban_project_user pu
          WHERE pu.kanban_project_id = p.id
            AND pu.user_id = $1
      )
  )
ORDER BY p.name, p.id, b.position, b.id, col.position, col.id, c.position, c.id
`

type GetAssignedCardsClosedRow struct {
	ProjectID       int64              `json:"project_id"`
	ProjectName     string             `json:"project_name"`
	BoardID         int64              `json:"board_id"`
	BoardTitle      string             `json:"board_title"`
	BoardPosition   float64            `json:"board_position"`
	ColumnID        int64              `json:"column_id"`
	ColumnTitle     string             `json:"column_title"`
	ColumnPosition  float64            `json:"column_position"`
	CardID          int64              `json:"card_id"`
	CardTitle       string             `json:"card_title"`
	CardPriority    pgtype.Text        `json:"card_priority"`
	CardDueDate     pgtype.Timestamptz `json:"card_due_date"`
	CardBorderColor pgtype.Text        `json:"card_border_color"`
	CardPosition    float64            `json:"card_position"`
}

func (q *Queries) GetAssignedCardsClosed(ctx context.Context, userID int64) ([]GetAssignedCardsClosedRow, error) {
	rows, err := q.db.Query(ctx, getAssignedCardsClosed, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAssignedCardsClosedRow{}
	for rows.Next() {
		var i GetAssignedCardsClosedRow
		if err := rows.Scan(
			&i.ProjectID,
			&i.ProjectName,
			&i.BoardID,
			&i.BoardTitle,
			&i.BoardPosition,
			&i.ColumnID,
			&i.ColumnTitle,
			&i.ColumnPosition,
			&i.CardID,
			&i.CardTitle,
			&i.CardPriority,
			&i.CardDueDate,
			&i.CardBorderColor,
			&i.CardPosition,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAssignedCardsOpen = `-- name: GetAssignedCardsOpen :many

SELECT
    p.id            AS project_id,
    p.name          AS project_name,
    b.id            AS board_id,
    b.title         AS board_title,
    b.position      AS board_position,
    col.id          AS column_id,
    col.title       AS column_title,
    col.position    AS column_position,
    c.id            AS card_id,
    c.title         AS card_title,
    c.priority      AS card_priority,
    c.due_date      AS card_due_date,
    c.border_color  AS card_border_color,
    c.position      AS card_position
FROM kanban_card_assignee ca
JOIN kanban_card    c   ON c.id  = ca.card_id
JOIN kanban_column  col ON col.id = c.column_id
JOIN kanban_board   b   ON b.id  = col.board_id
JOIN kanban_project p   ON p.id  = b.kanban_project_id
WHERE ca.user_id = $1
  AND c.completed_at IS NULL
  AND c.is_archived = FALSE
  AND b.deleted_at IS NULL
  AND p.deleted_at IS NULL
  AND (
      p.owner_id = $1
      OR EXISTS (
          SELECT 1 FROM kanban_project_user pu
          WHERE pu.kanban_project_id = p.id
            AND pu.user_id = $1
      )
  )
ORDER BY p.name, p.id, b.position, b.id, col.position, col.id, c.position, c.id
`

type GetAssignedCardsOpenRow struct {
	ProjectID       int64              `json:"project_id"`
	ProjectName     string             `json:"project_name"`
	BoardID         int64              `json:"board_id"`
	BoardTitle      string             `json:"board_title"`
	BoardPosition   float64            `json:"board_position"`
	ColumnID        int64              `json:"column_id"`
	ColumnTitle     string             `json:"column_title"`
	ColumnPosition  float64            `json:"column_position"`
	CardID          int64              `json:"card_id"`
	CardTitle       string             `json:"card_title"`
	CardPriority    pgtype.Text        `json:"card_priority"`
	CardDueDate     pgtype.Timestamptz `json:"card_due_date"`
	CardBorderColor pgtype.Text        `json:"card_border_color"`
	CardPosition    float64            `json:"card_position"`
}

// ==============================
// ASSIGNED TO ME (мои задачи / подзадачи)
// ==============================
func (q *Queries) GetAssignedCardsOpen(ctx context.Context, userID int64) ([]GetAssignedCardsOpenRow, error) {
	rows, err := q.db.Query(ctx, getAssignedCardsOpen, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAssignedCardsOpenRow{}
	for rows.Next() {
		var i GetAssignedCardsOpenRow
		if err := rows.Scan(
			&i.ProjectID,
			&i.ProjectName,
			&i.BoardID,
			&i.BoardTitle,
			&i.BoardPosition,
			&i.ColumnID,
			&i.ColumnTitle,
			&i.ColumnPosition,
			&i.CardID,
			&i.CardTitle,
			&i.CardPriority,
			&i.CardDueDate,
			&i.CardBorderColor,
			&i.CardPosition,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAssignedSubtasksClosed = `-- name: GetAssignedSubtasksClosed :many
SELECT
    s.id       AS subtask_id,
    s.title    AS subtask_title,
    s.status   AS subtask_status,
    s.position AS subtask_position,
    c.id       AS card_id,
    c.title    AS card_title,
    col.id     AS column_id,
    col.title  AS column_title,
    b.id       AS board_id,
    b.title    AS board_title,
    p.id       AS project_id,
    p.name     AS project_name
FROM kanban_card_subtask s
JOIN kanban_card    c   ON c.id  = s.card_id
JOIN kanban_column  col ON col.id = c.column_id
JOIN kanban_board   b   ON b.id  = col.board_id
JOIN kanban_project p   ON p.id  = b.kanban_project_id
WHERE s.user_id = $1::bigint
  AND s.status = 'done'
  AND b.deleted_at IS NULL
  AND p.deleted_at IS NULL
  AND (
      p.owner_id = $1::bigint
      OR EXISTS (
          SELECT 1 FROM kanban_project_user pu
          WHERE pu.kanban_project_id = p.id
            AND pu.user_id = $1::bigint
      )
  )
ORDER BY p.name, p.id, b.position, b.id, col.position, col.id, c.position, c.id, s.position, s.id
`

type GetAssignedSubtasksClosedRow struct {
	SubtaskID       int64   `json:"subtask_id"`
	SubtaskTitle    string  `json:"subtask_title"`
	SubtaskStatus   string  `json:"subtask_status"`
	SubtaskPosition float64 `json:"subtask_position"`
	CardID          int64   `json:"card_id"`
	CardTitle       string  `json:"card_title"`
	ColumnID        int64   `json:"column_id"`
	ColumnTitle     string  `json:"column_title"`
	BoardID         int64   `json:"board_id"`
	BoardTitle      string  `json:"board_title"`
	ProjectID       int64   `json:"project_id"`
	ProjectName     string  `json:"project_name"`
}

func (q *Queries) GetAssignedSubtasksClosed(ctx context.Context, dollar_1 int64) ([]GetAssignedSubtasksClosedRow, error) {
	rows, err := q.db.Query(ctx, getAssignedSubtasksClosed, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAssignedSubtasksClosedRow{}
	for rows.Next() {
		var i GetAssignedSubtasksClosedRow
		if err := rows.Scan(
			&i.SubtaskID,
			&i.SubtaskTitle,
			&i.SubtaskStatus,
			&i.SubtaskPosition,
			&i.CardID,
			&i.CardTitle,
			&i.ColumnID,
			&i.ColumnTitle,
			&i.BoardID,
			&i.BoardTitle,
			&i.ProjectID,
			&i.ProjectName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAssignedSubtasksOpen = `-- name: GetAssignedSubtasksOpen :many
SELECT
    s.id       AS subtask_id,
    s.title    AS subtask_title,
    s.status   AS subtask_status,
    s.position AS subtask_position,
    c.id       AS card_id,
    c.title    AS card_title,
    col.id     AS column_id,
    col.title  AS column_title,
    b.id       AS board_id,
    b.title    AS board_title,
    p.id       AS project_id,
    p.name     AS project_name
FROM kanban_card_subtask s
JOIN kanban_card    c   ON c.id  = s.card_id
JOIN kanban_column  col ON col.id = c.column_id
JOIN kanban_board   b   ON b.id  = col.board_id
JOIN kanban_project p   ON p.id  = b.kanban_project_id
WHERE s.user_id = $1::bigint
  AND s.status <> 'done'
  AND b.deleted_at IS NULL
  AND p.deleted_at IS NULL
  AND (
      p.owner_id = $1::bigint
      OR EXISTS (
          SELECT 1 FROM kanban_project_user pu
          WHERE pu.kanban_project_id = p.id
            AND pu.user_id = $1::bigint
      )
  )
ORDER BY p.name, p.id, b.position, b.id, col.position, col.id, c.position, c.id, s.position, s.id
`

type GetAssignedSubtasksOpenRow struct {
	SubtaskID       int64   `json:"subtask_id"`
	SubtaskTitle    string  `json:"subtask_title"`
	SubtaskStatus   string  `json:"subtask_status"`
	SubtaskPosition float64 `json:"subtask_position"`
	CardID          int64   `json:"card_id"`
	CardTitle       string  `json:"card_title"`
	ColumnID        int64   `json:"column_id"`
	ColumnTitle     string  `json:"column_title"`
	BoardID         int64   `json:"board_id"`
	BoardTitle      string  `json:"board_title"`
	ProjectID       int64   `json:"project_id"`
	ProjectName     string  `json:"project_name"`
}

func (q *Queries) GetAssignedSubtasksOpen(ctx context.Context, dollar_1 int64) ([]GetAssignedSubtasksOpenRow, error) {
	rows, err := q.db.Query(ctx, getAssignedSubtasksOpen, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAssignedSubtasksOpenRow{}
	for rows.Next() {
		var i GetAssignedSubtasksOpenRow
		if err := rows.Scan(
			&i.SubtaskID,
			&i.SubtaskTitle,
			&i.SubtaskStatus,
			&i.SubtaskPosition,
			&i.CardID,
			&i.CardTitle,
			&i.ColumnID,
			&i.ColumnTitle,
			&i.BoardID,
			&i.BoardTitle,
			&i.ProjectID,
			&i.ProjectName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAttachment = `-- name: GetAttachment :one

SELECT id, filename, storage_key, content_type, size_bytes, card_id, context, author_id, created_at FROM kanban_attachment
WHERE id = $1 LIMIT 1
`

// ==============================
// ATTACHMENTS
// ==============================
func (q *Queries) GetAttachment(ctx context.Context, id int64) (KanbanAttachment, error) {
	row := q.db.QueryRow(ctx, getAttachment, id)
	var i KanbanAttachment
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.StorageKey,
		&i.ContentType,
		&i.SizeBytes,
		&i.CardID,
		&i.Context,
		&i.AuthorID,
		&i.CreatedAt,
	)
	return i, err
}

const getAttachmentsByCard = `-- name: GetAttachmentsByCard :many
SELECT id, filename, storage_key, content_type, size_bytes, card_id, context, author_id, created_at FROM kanban_attachment
WHERE card_id = $1 AND context = $2
ORDER BY created_at ASC
`

type GetAttachmentsByCardParams struct {
	CardID  int64  `json:"card_id"`
	Context string `json:"context"`
}

func (q *Queries) GetAttachmentsByCard(ctx context.Context, arg GetAttachmentsByCardParams) ([]KanbanAttachment, error) {
	rows, err := q.db.Query(ctx, getAttachmentsByCard, arg.CardID, arg.Context)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KanbanAttachment{}
	for rows.Next() {
		var i KanbanAttachment
		if err := rows.Scan(
			&i.ID,
			&i.Filename,
			&i.StorageKey,
			&i.ContentType,
			&i.SizeBytes,
			&i.CardID,
			&i.Context,
			&i.AuthorID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBoard = `-- name: GetBoard :one

SELECT id, title, position, kanban_project_id, created_by_id, created_at, updated_at, deleted_at FROM kanban_board
WHERE id = $1 AND deleted_at IS NULL LIMIT 1
`

// ==============================
// BOARDS
// ==============================
func (q *Queries) GetBoard(ctx context.Context, id int64) (KanbanBoard, error) {
	row := q.db.QueryRow(ctx, getBoard, id)
	var i KanbanBoard
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Position,
		&i.KanbanProjectID,
		&i.CreatedByID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getBoardsByProject = `-- name: GetBoardsByProject :many
SELECT id, title, position, kanban_project_id, created_by_id, created_at, updated_at, deleted_at FROM kanban_board
WHERE kanban_project_id = $1 AND deleted_at IS NULL
ORDER BY position ASC
`

func (q *Queries) GetBoardsByProject(ctx context.Context, kanbanProjectID int64) ([]KanbanBoard, error) {
	rows, err := q.db.Query(ctx, getBoardsByProject, kanbanProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KanbanBoard{}
	for rows.Next() {
		var i KanbanBoard
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Position,
			&i.KanbanProjectID,
			&i.CreatedByID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCard = `-- name: GetCard :one

SELECT id, title, description, position, due_date, priority, is_archived, archived_at, archived_by_id, completed_at, completed_by_id, column_id, created_by_id, border_color, created_at, updated_at FROM kanban_card
WHERE id = $1 LIMIT 1
`

// ==============================
// CARDS
// ==============================
func (q *Queries) GetCard(ctx context.Context, id int64) (KanbanCard, error) {
	row := q.db.QueryRow(ctx, getCard, id)
	var i KanbanCard
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Position,
		&i.DueDate,
		&i.Priority,
		&i.IsArchived,
		&i.ArchivedAt,
		&i.ArchivedByID,
		&i.CompletedAt,
		&i.CompletedByID,
		&i.ColumnID,
		&i.CreatedByID,
		&i.BorderColor,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCardAssignees = `-- name: GetCardAssignees :many

SELECT user_id FROM kanban_card_assignee
WHERE card_id = $1
`

// ==============================
// CARD ASSIGNEES
// ==============================
func (q *Queries) GetCardAssignees(ctx context.Context, cardID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, getCardAssignees, cardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var user_id int64
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCardAssigneesByCardIDs = `-- name: GetCardAssigneesByCardIDs :many
SELECT card_id, user_id FROM kanban_card_assignee
WHERE card_id = ANY($1::bigint[])
`

func (q *Queries) GetCardAssigneesByCardIDs(ctx context.Context, dollar_1 []int64) ([]KanbanCardAssignee, error) {
	rows, err := q.db.Query(ctx, getCardAssigneesByCardIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KanbanCardAssignee{}
	for rows.Next() {
		var i KanbanCardAssignee
		if err := rows.Scan(&i.CardID, &i.UserID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCardLabels = `-- name: GetCardLabels :many

SELECT kanban_label_id FROM kanban_card_label
WHERE kanban_card_id = $1
`

// ==============================
// CARD LABELS
// ==============================
func (q *Queries) GetCardLabels(ctx context.Context, kanbanCardID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, getCardLabels, kanbanCardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var kanban_label_id int64
		if err := rows.Scan(&kanban_label_id); err != nil {
			return nil, err
		}
		items = append(items, kanban_label_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCardLabelsByCardIDs = `-- name: GetCardLabelsByCardIDs :many
SELECT kanban_card_id, kanban_label_id FROM kanban_card_label
WHERE kanban_card_id = ANY($1::bigint[])
`

func (q *Queries) GetCardLabelsByCardIDs(ctx context.Context, dollar_1 []int64) ([]KanbanCardLabel, error) {
	rows, err := q.db.Query(ctx, getCardLabelsByCardIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KanbanCardLabel{}
	for rows.Next() {
		var i KanbanCardLabel
		if err := rows.Scan(&i.KanbanCardID, &i.KanbanLabelID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCardsByBoard = `-- name: GetCardsByBoard :many
SELECT c.id, c.title, c.description, c.position, c.due_date, c.priority, c.is_archived, c.archived_at, c.archived_by_id, c.completed_at, c.completed_by_id, c.column_id, c.created_by_id, c.border_color, c.created_at, c.updated_at FROM kanban_card c
JOIN kanban_column col ON col.id = c.column_id
WHERE col.board_id = $1 AND c.is_archived = FALSE
ORDER BY col.position ASC, c.position ASC
`

func (q *Queries) GetCardsByBoard(ctx context.Context, boardID int64) ([]KanbanCard, error) {
	rows, err := q.db.Query(ctx, getCardsByBoard, boardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KanbanCard{}
	for rows.Next() {
		var i KanbanCard
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Position,
			&i.DueDate,
			&i.Priority,
			&i.IsArchived,
			&i.ArchivedAt,
			&i.ArchivedByID,
			&i.CompletedAt,
			&i.CompletedByID,
			&i.ColumnID,
			&i.CreatedByID,
			&i.BorderColor,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCardsByColumn = `-- name: GetCardsByColumn :many
SELECT id, title, description, position, due_date, priority, is_archived, archived_at, archived_by_id, completed_at, completed_by_id, column_id, created_by_id, border_color, created_at, updated_at FROM kanban_card
WHERE column_id = $1 AND is_archived = FALSE
ORDER BY position ASC
`

func (q *Queries) GetCardsByColumn(ctx context.Context, columnID int64) ([]KanbanCard, error) {
	rows, err := q.db.Query(ctx, getCardsByColumn, columnID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KanbanCard{}
	for rows.Next() {
		var i KanbanCard
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Position,
			&i.DueDate,
			&i.Priority,
			&i.IsArchived,
			&i.ArchivedAt,
			&i.ArchivedByID,
			&i.CompletedAt,
			&i.CompletedByID,
			&i.ColumnID,
			&i.CreatedByID,
			&i.BorderColor,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChatAttachmentCountsByCardIDs = `-- name: GetChatAttachmentCountsByCardIDs :many
SELECT card_id, COUNT(*) AS count
FROM kanban_attachment
WHERE card_id = ANY($1::bigint[]) AND context = 'chat'
GROUP BY card_id
`

type GetChatAttachmentCountsByCardIDsRow struct {
	CardID int64 `json:"card_id"`
	Count  int64 `json:"count"`
}

func (q *Queries) GetChatAttachmentCountsByCardIDs(ctx context.Context, dollar_1 []int64) ([]GetChatAttachmentCountsByCardIDsRow, error) {
	rows, err := q.db.Query(ctx, getChatAttachmentCountsByCardIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetChatAttachmentCountsByCardIDsRow{}
	for rows.Next() {
		var i GetChatAttachmentCountsByCardIDsRow
		if err := rows.Scan(&i.CardID, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getColumn = `-- name: GetColumn :one

SELECT id, title, header_color, position, board_id FROM kanban_column
WHERE id = $1 LIMIT 1
`

// ==============================
// COLUMNS
// ==============================
func (q *Queries) GetColumn(ctx context.Context, id int64) (KanbanColumn, error) {
	row := q.db.QueryRow(ctx, getColumn, id)
	var i KanbanColumn
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.HeaderColor,
		&i.Position,
		&i.BoardID,
	)
	return i, err
}

const getColumnsByBoard = `-- name: GetColumnsByBoard :many
SELECT id, title, header_color, position, board_id FROM kanban_column
WHERE board_id = $1
ORDER BY position ASC
`

func (q *Queries) GetColumnsByBoard(ctx context.Context, boardID int64) ([]KanbanColumn, error) {
	rows, err := q.db.Query(ctx, getColumnsByBoard, boardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KanbanColumn{}
	for rows.Next() {
		var i KanbanColumn
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.HeaderColor,
			&i.Position,
			&i.BoardID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getComment = `-- name: GetComment :one

SELECT id, body, card_id, author_id, created_at, updated_at FROM kanban_card_comment
WHERE id = $1 LIMIT 1
`

// ==============================
// COMMENTS
// ==============================
func (q *Queries) GetComment(ctx context.Context, id int64) (KanbanCardComment, error) {
	row := q.db.QueryRow(ctx, getComment, id)
	var i KanbanCardComment
	err := row.Scan(
		&i.ID,
		&i.Body,
		&i.CardID,
		&i.AuthorID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCommentCountsByCardIDs = `-- name: GetCommentCountsByCardIDs :many
SELECT card_id, COUNT(*) AS count
FROM kanban_card_comment
WHERE card_id = ANY($1::bigint[])
GROUP BY card_id
`

type GetCommentCountsByCardIDsRow struct {
	CardID int64 `json:"card_id"`
	Count  int64 `json:"count"`
}

func (q *Queries) GetCommentCountsByCardIDs(ctx context.Context, dollar_1 []int64) ([]GetCommentCountsByCardIDsRow, error) {
	rows, err := q.db.Query(ctx, getCommentCountsByCardIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCommentCountsByCardIDsRow{}
	for rows.Next() {
		var i GetCommentCountsByCardIDsRow
		if err := rows.Scan(&i.CardID, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCommentsByCard = `-- name: GetCommentsByCard :many
SELECT id, body, card_id, author_id, created_at, updated_at FROM kanban_card_comment
WHERE card_id = $1
ORDER BY created_at ASC
`

func (q *Queries) GetCommentsByCard(ctx context.Context, cardID int64) ([]KanbanCardComment, error) {
	rows, err := q.db.Query(ctx, getCommentsByCard, cardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KanbanCardComment{}
	for rows.Next() {
		var i KanbanCardComment
		if err := rows.Scan(
			&i.ID,
			&i.Body,
			&i.CardID,
			&i.AuthorID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLabel = `-- name: GetLabel :one

SELECT id, name, color, board_id FROM kanban_label
WHERE id = $1 LIMIT 1
`

// ==============================
// LABELS
// ==============================
func (q *Queries) GetLabel(ctx context.Context, id int64) (KanbanLabel, error) {
	row := q.db.QueryRow(ctx, getLabel, id)
	var i KanbanLabel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.BoardID,
	)
	return i, err
}

const getLabelsByBoard = `-- name: GetLabelsByBoard :many
SELECT id, name, color, board_id FROM kanban_label
WHERE board_id = $1
`

func (q *Queries) GetLabelsByBoard(ctx context.Context, boardID int64) ([]KanbanLabel, error) {
	rows, err := q.db.Query(ctx, getLabelsByBoard, boardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KanbanLabel{}
	for rows.Next() {
		var i KanbanLabel
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Color,
			&i.BoardID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProject = `-- name: GetProject :one
SELECT id, name, description, owner_id, created_by_id, created_at, updated_at, deleted_at FROM kanban_project
WHERE id = $1 AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetProject(ctx context.Context, id int64) (KanbanProject, error) {
	row := q.db.QueryRow(ctx, getProject, id)
	var i KanbanProject
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.OwnerID,
		&i.CreatedByID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getProjectFolders = `-- name: GetProjectFolders :many

SELECT id, name, user_id, position, created_at, updated_at FROM kanban_project_user_folder
WHERE user_id = $1 ORDER BY position ASC
`

// ==============================
// PROJECT FOLDERS
// ==============================
func (q *Queries) GetProjectFolders(ctx context.Context, userID int64) ([]KanbanProjectUserFolder, error) {
	rows, err := q.db.Query(ctx, getProjectFolders, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KanbanProjectUserFolder{}
	for rows.Next() {
		var i KanbanProjectUserFolder
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.UserID,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProjectIDByCard = `-- name: GetProjectIDByCard :one
SELECT b.kanban_project_id FROM kanban_card card
JOIN kanban_column c ON card.column_id = c.id
JOIN kanban_board b ON c.board_id = b.id
WHERE card.id = $1
`

func (q *Queries) GetProjectIDByCard(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, getProjectIDByCard, id)
	var kanban_project_id int64
	err := row.Scan(&kanban_project_id)
	return kanban_project_id, err
}

const getProjectIDByColumn = `-- name: GetProjectIDByColumn :one
SELECT b.kanban_project_id FROM kanban_column c
JOIN kanban_board b ON c.board_id = b.id
WHERE c.id = $1
`

func (q *Queries) GetProjectIDByColumn(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, getProjectIDByColumn, id)
	var kanban_project_id int64
	err := row.Scan(&kanban_project_id)
	return kanban_project_id, err
}

const getProjectIDByLabel = `-- name: GetProjectIDByLabel :one
SELECT b.kanban_project_id as project_id
FROM kanban_label l
JOIN kanban_board b ON l.board_id = b.id
WHERE l.id = $1
`

func (q *Queries) GetProjectIDByLabel(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, getProjectIDByLabel, id)
	var project_id int64
	err := row.Scan(&project_id)
	return project_id, err
}

const getProjectIDBySubtask = `-- name: GetProjectIDBySubtask :one
SELECT b.kanban_project_id as project_id
FROM kanban_card_subtask s
JOIN kanban_card c ON s.card_id = c.id
JOIN kanban_column col ON c.column_id = col.id
JOIN kanban_board b ON col.board_id = b.id
WHERE s.id = $1
`

func (q *Queries) GetProjectIDBySubtask(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, getProjectIDBySubtask, id)
	var project_id int64
	err := row.Scan(&project_id)
	return project_id, err
}

const getProjectMember = `-- name: GetProjectMember :one
SELECT id, kanban_project_id, user_id, role, folder_id, position FROM kanban_project_user
WHERE kanban_project_id = $1 AND user_id = $2
`

type GetProjectMemberParams struct {
	KanbanProjectID int64 `json:"kanban_project_id"`
	UserID          int64 `json:"user_id"`
}

func (q *Queries) GetProjectMember(ctx context.Context, arg GetProjectMemberParams) (KanbanProjectUser, error) {
	row := q.db.QueryRow(ctx, getProjectMember, arg.KanbanProjectID, arg.UserID)
	var i KanbanProjectUser
	err := row.Scan(
		&i.ID,
		&i.KanbanProjectID,
		&i.UserID,
		&i.Role,
		&i.FolderID,
		&i.Position,
	)
	return i, err
}

const getProjectMembers = `-- name: GetProjectMembers :many

SELECT id, kanban_project_id, user_id, role, folder_id, position FROM kanban_project_user
WHERE kanban_project_id = $1
`

// ==============================
// PROJECT MEMBERS
// ==============================
func (q *Queries) GetProjectMembers(ctx context.Context, kanbanProjectID int64) ([]KanbanProjectUser, error) {
	rows, err := q.db.Query(ctx, getProjectMembers, kanbanProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KanbanProjectUser{}
	for rows.Next() {
		var i KanbanProjectUser
		if err := rows.Scan(
			&i.ID,
			&i.KanbanProjectID,
			&i.UserID,
			&i.Role,
			&i.FolderID,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSubtask = `-- name: GetSubtask :one

SELECT id, title, status, position, card_id, user_id FROM kanban_card_subtask
WHERE id = $1 LIMIT 1
`

// ==============================
// SUBTASKS
// ==============================
func (q *Queries) GetSubtask(ctx context.Context, id int64) (KanbanCardSubtask, error) {
	row := q.db.QueryRow(ctx, getSubtask, id)
	var i KanbanCardSubtask
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Status,
		&i.Position,
		&i.CardID,
		&i.UserID,
	)
	return i, err
}

const getSubtaskCountsByCardIDs = `-- name: GetSubtaskCountsByCardIDs :many
SELECT card_id,
       COUNT(*) AS total,
       COUNT(*) FILTER (WHERE LOWER(status) = 'done') AS done
FROM kanban_card_subtask
WHERE card_id = ANY($1::bigint[])
GROUP BY card_id
`

type GetSubtaskCountsByCardIDsRow struct {
	CardID int64 `json:"card_id"`
	Total  int64 `json:"total"`
	Done   int64 `json:"done"`
}

func (q *Queries) GetSubtaskCountsByCardIDs(ctx context.Context, dollar_1 []int64) ([]GetSubtaskCountsByCardIDsRow, error) {
	rows, err := q.db.Query(ctx, getSubtaskCountsByCardIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSubtaskCountsByCardIDsRow{}
	for rows.Next() {
		var i GetSubtaskCountsByCardIDsRow
		if err := rows.Scan(&i.CardID, &i.Total, &i.Done); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSubtasksByCard = `-- name: GetSubtasksByCard :many
SELECT id, title, status, position, card_id, user_id FROM kanban_card_subtask
WHERE card_id = $1
ORDER BY position ASC
`

func (q *Queries) GetSubtasksByCard(ctx context.Context, cardID int64) ([]KanbanCardSubtask, error) {
	rows, err := q.db.Query(ctx, getSubtasksByCard, cardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KanbanCardSubtask{}
	for rows.Next() {
		var i KanbanCardSubtask
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Status,
			&i.Position,
			&i.CardID,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hasCardsByColumn = `-- name: HasCardsByColumn :one
SELECT EXISTS(
    SELECT 1 FROM kanban_card WHERE column_id = $1 AND is_archived = FALSE
)
`

func (q *Queries) HasCardsByColumn(ctx context.Context, columnID int64) (bool, error) {
	row := q.db.QueryRow(ctx, hasCardsByColumn, columnID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const hasColumnsByBoard = `-- name: HasColumnsByBoard :one
SELECT EXISTS(
    SELECT 1 FROM kanban_column WHERE board_id = $1
)
`

func (q *Queries) HasColumnsByBoard(ctx context.Context, boardID int64) (bool, error) {
	row := q.db.QueryRow(ctx, hasColumnsByBoard, boardID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const rebalanceColumnCards = `-- name: RebalanceColumnCards :exec
WITH ranked AS (
  SELECT id, ROW_NUMBER() OVER(ORDER BY position ASC, id ASC) as rn
  FROM kanban_card
  WHERE kanban_card.column_id = $1 AND kanban_card.is_archived = FALSE
)
UPDATE kanban_card
SET position = ranked.rn * 65536.0
FROM ranked
WHERE kanban_card.id = ranked.id
`

func (q *Queries) RebalanceColumnCards(ctx context.Context, columnID int64) error {
	_, err := q.db.Exec(ctx, rebalanceColumnCards, columnID)
	return err
}

const removeCardAssignee = `-- name: RemoveCardAssignee :exec
DELETE FROM kanban_card_assignee
WHERE card_id = $1 AND user_id = $2
`

type RemoveCardAssigneeParams struct {
	CardID int64 `json:"card_id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) RemoveCardAssignee(ctx context.Context, arg RemoveCardAssigneeParams) error {
	_, err := q.db.Exec(ctx, removeCardAssignee, arg.CardID, arg.UserID)
	return err
}

const removeCardLabel = `-- name: RemoveCardLabel :exec
DELETE FROM kanban_card_label
WHERE kanban_card_id = $1 AND kanban_label_id = $2
`

type RemoveCardLabelParams struct {
	KanbanCardID  int64 `json:"kanban_card_id"`
	KanbanLabelID int64 `json:"kanban_label_id"`
}

func (q *Queries) RemoveCardLabel(ctx context.Context, arg RemoveCardLabelParams) error {
	_, err := q.db.Exec(ctx, removeCardLabel, arg.KanbanCardID, arg.KanbanLabelID)
	return err
}

const removeProjectMember = `-- name: RemoveProjectMember :exec
DELETE FROM kanban_project_user
WHERE kanban_project_id = $1 AND user_id = $2
`

type RemoveProjectMemberParams struct {
	KanbanProjectID int64 `json:"kanban_project_id"`
	UserID          int64 `json:"user_id"`
}

func (q *Queries) RemoveProjectMember(ctx context.Context, arg RemoveProjectMemberParams) error {
	_, err := q.db.Exec(ctx, removeProjectMember, arg.KanbanProjectID, arg.UserID)
	return err
}

const replaceProjectMembers = `-- name: ReplaceProjectMembers :exec
DELETE FROM kanban_project_user
WHERE kanban_project_id = $1
`

func (q *Queries) ReplaceProjectMembers(ctx context.Context, kanbanProjectID int64) error {
	_, err := q.db.Exec(ctx, replaceProjectMembers, kanbanProjectID)
	return err
}

const updateBoard = `-- name: UpdateBoard :one
UPDATE kanban_board
SET title = $1, position = $2, updated_at = CURRENT_TIMESTAMP
WHERE id = $3 AND deleted_at IS NULL
RETURNING id, title, position, kanban_project_id, created_by_id, created_at, updated_at, deleted_at
`

type UpdateBoardParams struct {
	Title    string  `json:"title"`
	Position float64 `json:"position"`
	ID       int64   `json:"id"`
}

func (q *Queries) UpdateBoard(ctx context.Context, arg UpdateBoardParams) (KanbanBoard, error) {
	row := q.db.QueryRow(ctx, updateBoard, arg.Title, arg.Position, arg.ID)
	var i KanbanBoard
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Position,
		&i.KanbanProjectID,
		&i.CreatedByID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateCard = `-- name: UpdateCard :one
UPDATE kanban_card
SET title = $1, description = $2, position = $3, due_date = $4, priority = $5, is_archived = $6, archived_at = $7, archived_by_id = $8, completed_at = $9, completed_by_id = $10, column_id = $11, border_color = $12, updated_at = CURRENT_TIMESTAMP
WHERE id = $13
RETURNING id, title, description, position, due_date, priority, is_archived, archived_at, archived_by_id, completed_at, completed_by_id, column_id, created_by_id, border_color, created_at, updated_at
`

type UpdateCardParams struct {
	Title         string             `json:"title"`
	Description   pgtype.Text        `json:"description"`
	Position      float64            `json:"position"`
	DueDate       pgtype.Timestamptz `json:"due_date"`
	Priority      pgtype.Text        `json:"priority"`
	IsArchived    bool               `json:"is_archived"`
	ArchivedAt    pgtype.Timestamptz `json:"archived_at"`
	ArchivedByID  pgtype.Int8        `json:"archived_by_id"`
	CompletedAt   pgtype.Timestamptz `json:"completed_at"`
	CompletedByID pgtype.Int8        `json:"completed_by_id"`
	ColumnID      int64              `json:"column_id"`
	BorderColor   pgtype.Text        `json:"border_color"`
	ID            int64              `json:"id"`
}

func (q *Queries) UpdateCard(ctx context.Context, arg UpdateCardParams) (KanbanCard, error) {
	row := q.db.QueryRow(ctx, updateCard,
		arg.Title,
		arg.Description,
		arg.Position,
		arg.DueDate,
		arg.Priority,
		arg.IsArchived,
		arg.ArchivedAt,
		arg.ArchivedByID,
		arg.CompletedAt,
		arg.CompletedByID,
		arg.ColumnID,
		arg.BorderColor,
		arg.ID,
	)
	var i KanbanCard
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Position,
		&i.DueDate,
		&i.Priority,
		&i.IsArchived,
		&i.ArchivedAt,
		&i.ArchivedByID,
		&i.CompletedAt,
		&i.CompletedByID,
		&i.ColumnID,
		&i.CreatedByID,
		&i.BorderColor,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateColumn = `-- name: UpdateColumn :one
UPDATE kanban_column
SET title = $1, header_color = $2, position = $3
WHERE id = $4
RETURNING id, title, header_color, position, board_id
`

type UpdateColumnParams struct {
	Title       string  `json:"title"`
	HeaderColor string  `json:"header_color"`
	Position    float64 `json:"position"`
	ID          int64   `json:"id"`
}

func (q *Queries) UpdateColumn(ctx context.Context, arg UpdateColumnParams) (KanbanColumn, error) {
	row := q.db.QueryRow(ctx, updateColumn,
		arg.Title,
		arg.HeaderColor,
		arg.Position,
		arg.ID,
	)
	var i KanbanColumn
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.HeaderColor,
		&i.Position,
		&i.BoardID,
	)
	return i, err
}

const updateComment = `-- name: UpdateComment :one
UPDATE kanban_card_comment
SET body = $1, updated_at = CURRENT_TIMESTAMP
WHERE id = $2
RETURNING id, body, card_id, author_id, created_at, updated_at
`

type UpdateCommentParams struct {
	Body string `json:"body"`
	ID   int64  `json:"id"`
}

func (q *Queries) UpdateComment(ctx context.Context, arg UpdateCommentParams) (KanbanCardComment, error) {
	row := q.db.QueryRow(ctx, updateComment, arg.Body, arg.ID)
	var i KanbanCardComment
	err := row.Scan(
		&i.ID,
		&i.Body,
		&i.CardID,
		&i.AuthorID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProject = `-- name: UpdateProject :one
UPDATE kanban_project
SET name = $1, description = $2, updated_at = CURRENT_TIMESTAMP
WHERE id = $3 AND deleted_at IS NULL
RETURNING id, name, description, owner_id, created_by_id, created_at, updated_at, deleted_at
`

type UpdateProjectParams struct {
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	ID          int64       `json:"id"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (KanbanProject, error) {
	row := q.db.QueryRow(ctx, updateProject, arg.Name, arg.Description, arg.ID)
	var i KanbanProject
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.OwnerID,
		&i.CreatedByID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateProjectFolder = `-- name: UpdateProjectFolder :one
UPDATE kanban_project_user_folder
SET name = $1, position = $2, updated_at = CURRENT_TIMESTAMP
WHERE id = $3
RETURNING id, name, user_id, position, created_at, updated_at
`

type UpdateProjectFolderParams struct {
	Name     string  `json:"name"`
	Position float64 `json:"position"`
	ID       int64   `json:"id"`
}

func (q *Queries) UpdateProjectFolder(ctx context.Context, arg UpdateProjectFolderParams) (KanbanProjectUserFolder, error) {
	row := q.db.QueryRow(ctx, updateProjectFolder, arg.Name, arg.Position, arg.ID)
	var i KanbanProjectUserFolder
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.UserID,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProjectMemberRole = `-- name: UpdateProjectMemberRole :exec
UPDATE kanban_project_user
SET role = $3
WHERE kanban_project_id = $1 AND user_id = $2
`

type UpdateProjectMemberRoleParams struct {
	KanbanProjectID int64  `json:"kanban_project_id"`
	UserID          int64  `json:"user_id"`
	Role            string `json:"role"`
}

func (q *Queries) UpdateProjectMemberRole(ctx context.Context, arg UpdateProjectMemberRoleParams) error {
	_, err := q.db.Exec(ctx, updateProjectMemberRole, arg.KanbanProjectID, arg.UserID, arg.Role)
	return err
}

const updateSubtask = `-- name: UpdateSubtask :one
UPDATE kanban_card_subtask
SET title = $1, status = $2, position = $3, user_id = $4
WHERE id = $5
RETURNING id, title, status, position, card_id, user_id
`

type UpdateSubtaskParams struct {
	Title    string      `json:"title"`
	Status   string      `json:"status"`
	Position float64     `json:"position"`
	UserID   pgtype.Int8 `json:"user_id"`
	ID       int64       `json:"id"`
}

func (q *Queries) UpdateSubtask(ctx context.Context, arg UpdateSubtaskParams) (KanbanCardSubtask, error) {
	row := q.db.QueryRow(ctx, updateSubtask,
		arg.Title,
		arg.Status,
		arg.Position,
		arg.UserID,
		arg.ID,
	)
	var i KanbanCardSubtask
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Status,
		&i.Position,
		&i.CardID,
		&i.UserID,
	)
	return i, err
}
